<h2>Dear <?=$this->name?>,</h2>

<p>
  You have signed up for the setup team at Fastaval 2023!
</p>

<p>
  Set-up starts at 10 AM on Monday, April 3rd. When you arrive, please report your arrival to the set-up manager inside
  the main entrance, so we know how many people to cook for. Please also let us know what you can and cannot do. For
  example, lifting things.
</p>

<p>
  During setup, there wil be the usual 3 meals, plus various snacks. 
  On Facebook there is a group for everyone involved in the setup. It's called "Fastaval opsætning" 
  (<a href="https://www.facebook.com/groups/1000922983874153">https://www.facebook.com/groups/1000922983874153</a>).
  If you can't find the group, please send a mail to <a href="mailto:broechnern1502@gmail.com">broechnern1502@gmail.com</a>. 
  The group provides important information and coordination during setup. Therefore, we recommend that the entire setup
  team joins the FB group. Notably if you have allergies or the like, make sure to let us know in the post with the 'poll'
  about what you can't eat.
</p>

<p>
  Everyone must be present for the meals and stay seated until we're done with public announcements. We'll keep it
  relevant and brief. 
</p>

<p>
  In the evening we'll be socializing with beer, soft drinks, chips and possibly some board games. Further details will
  be announced during the meals.
</p>

<p>
  Accommodation during the setup days will be in the smaller sports halls at the gymnasium. It will be possible to find a
  spot in these halls from Monday in the afternoon. These halls serve as organizer and youth dorms during Fastaval, so
  expect being asked to move your stuff out on Wednesday morning.
</p>

<p>
  Thank you so much for helping to set up our very own Fastaval!
</p>

<p>
  Kind Regards, the main organizers and set-up managers
</p>