<h2>Kære <?=$this->name?>,</h2>

<p>
  Du har tilmeldt dig opsætningsholdet på Fastaval 2023!
</p>

<p>
  Opsætning starter kl. 10:00 mandag d. 3. april. Når du ankommer skal du inden for hovedindgangen melde din ankomst til
  opsætningsansvarlige, så vi ved hvor mange der skal laves mad til. Sig også gerne her, hvad du kan og ikke kan.
  Eksempelvis løfte på ting.
</p>

<p>
  Under opsætning er der de sædvanlige 3 måltider, plus diverse snacks.<br>
  På Facebook er der en gruppe for alle som er med til opsætning. Den hedder “Fastaval opsætning”
  (<a href="https://www.facebook.com/groups/1000922983874153">https://www.facebook.com/groups/1000922983874153</a>).<br>
  Kan du ikke finde fb-gruppen, så skriv til <a href="mailto:broechnern1502@gmail.com">broechnern1502@gmail.com</a>.<br> 
  I gruppen kommer der vigtig information og koordinering løbende under opsætning. Derfor anbefaler vi hele
  opsætningsholdet at være en del af fb-gruppen. Særligt hvis du har allergier eller lignende skal du sørge for at gøre
  os opmærksom på det i opslaget med 'meningsmåling' om hvad man ikke kan spise. 
</p>

<p>
  Alle skal være til stede til måltiderne og blive siddende til der har været fælles beskeder. Vi holder det relevant og
  kort.  
</p>

<p>
  Om aften hygger vi med øl, sodavand, chips og evt. lidt brætspil. Der bliver meldt yderligere ud ved beskederne under
  måltider.
</p>

<p>
  Overnatning i opsætningsdagene er i gymnasiets små gymnastiksale. Det vil først være muligt at finde en plads i
  sovesalen mandag ud på eftermiddagen. Disse sovesale er arrangør- og ungdomssovesale under Fastaval, så forvent at
  blive bedt om at rykke dine ting ud onsdag morgen.
</p>

<p>
  Tusind tak for at du vil hjælpe med at sætte vores alle sammens Fastaval op!
</p>

<p>
  Mvh. hovedarrangørerne og opsætningsanvarlige
</p>