DROP TABLE IF EXISTS idtemplates_items;
DROP TABLE IF EXISTS idtemplates;
CREATE TABLE idtemplates (
  id int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL DEFAULT '',
  background VARCHAR(256) NOT NULL DEFAULT '' 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE idtemplates_items (
  id int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  template_id INT UNSIGNED NOT NULL,
  itemtype ENUM ('photo', 'text', 'barcode') NOT NULL,
  x INT UNSIGNED NOT NULL,
  y INT UNSIGNED NOT NULL,
  width INT UNSIGNED NOT NULL,
  height INT UNSIGNED NOT NULL,
  rotation INT NOT NULL DEFAULT 0,
  datasource VARCHAR(64) NOT NULL DEFAULT '',
  CONSTRAINT FOREIGN KEY template (template_id) REFERENCES idtemplates (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
