CREATE TABLE countries (
  code CHAR(2) PRIMARY KEY,
  name_en TEXT,
  name_da TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- list created from php-intl ResourceBundle::getLocales and Locale::getDisplayRegion
INSERT INTO countries (code, name_en, name_da) VALUES('AF', 'Afghanistan', 'Afghanistan');
INSERT INTO countries (code, name_en, name_da) VALUES('AL', 'Albania', 'Albanien');
INSERT INTO countries (code, name_en, name_da) VALUES('DZ', 'Algeria', 'Algeriet');
INSERT INTO countries (code, name_en, name_da) VALUES('AS', 'American Samoa', 'Amerikansk Samoa');
INSERT INTO countries (code, name_en, name_da) VALUES('AD', 'Andorra', 'Andorra');
INSERT INTO countries (code, name_en, name_da) VALUES('AO', 'Angola', 'Angola');
INSERT INTO countries (code, name_en, name_da) VALUES('AI', 'Anguilla', 'Anguilla');
INSERT INTO countries (code, name_en, name_da) VALUES('AG', 'Antigua & Barbuda', 'Antigua og Barbuda');
INSERT INTO countries (code, name_en, name_da) VALUES('AR', 'Argentina', 'Argentina');
INSERT INTO countries (code, name_en, name_da) VALUES('AM', 'Armenia', 'Armenien');
INSERT INTO countries (code, name_en, name_da) VALUES('AW', 'Aruba', 'Aruba');
INSERT INTO countries (code, name_en, name_da) VALUES('AU', 'Australia', 'Australien');
INSERT INTO countries (code, name_en, name_da) VALUES('AT', 'Austria', 'Østrig');
INSERT INTO countries (code, name_en, name_da) VALUES('AZ', 'Azerbaijan', 'Aserbajdsjan');
INSERT INTO countries (code, name_en, name_da) VALUES('BS', 'Bahamas', 'Bahamas');
INSERT INTO countries (code, name_en, name_da) VALUES('BH', 'Bahrain', 'Bahrain');
INSERT INTO countries (code, name_en, name_da) VALUES('BD', 'Bangladesh', 'Bangladesh');
INSERT INTO countries (code, name_en, name_da) VALUES('BB', 'Barbados', 'Barbados');
INSERT INTO countries (code, name_en, name_da) VALUES('BY', 'Belarus', 'Hviderusland');
INSERT INTO countries (code, name_en, name_da) VALUES('BE', 'Belgium', 'Belgien');
INSERT INTO countries (code, name_en, name_da) VALUES('BZ', 'Belize', 'Belize');
INSERT INTO countries (code, name_en, name_da) VALUES('BJ', 'Benin', 'Benin');
INSERT INTO countries (code, name_en, name_da) VALUES('BM', 'Bermuda', 'Bermuda');
INSERT INTO countries (code, name_en, name_da) VALUES('BT', 'Bhutan', 'Bhutan');
INSERT INTO countries (code, name_en, name_da) VALUES('BO', 'Bolivia', 'Bolivia');
INSERT INTO countries (code, name_en, name_da) VALUES('BA', 'Bosnia & Herzegovina', 'Bosnien-Hercegovina');
INSERT INTO countries (code, name_en, name_da) VALUES('BW', 'Botswana', 'Botswana');
INSERT INTO countries (code, name_en, name_da) VALUES('BR', 'Brazil', 'Brasilien');
INSERT INTO countries (code, name_en, name_da) VALUES('IO', 'British Indian Ocean Territory', 'Det Britiske Territorium i Det Indiske Ocean');
INSERT INTO countries (code, name_en, name_da) VALUES('VG', 'British Virgin Islands', 'De Britiske Jomfruøer');
INSERT INTO countries (code, name_en, name_da) VALUES('BN', 'Brunei', 'Brunei');
INSERT INTO countries (code, name_en, name_da) VALUES('BG', 'Bulgaria', 'Bulgarien');
INSERT INTO countries (code, name_en, name_da) VALUES('BF', 'Burkina Faso', 'Burkina Faso');
INSERT INTO countries (code, name_en, name_da) VALUES('BI', 'Burundi', 'Burundi');
INSERT INTO countries (code, name_en, name_da) VALUES('KH', 'Cambodia', 'Cambodja');
INSERT INTO countries (code, name_en, name_da) VALUES('CM', 'Cameroon', 'Cameroun');
INSERT INTO countries (code, name_en, name_da) VALUES('CA', 'Canada', 'Canada');
INSERT INTO countries (code, name_en, name_da) VALUES('IC', 'Canary Islands', 'Kanariske øer');
INSERT INTO countries (code, name_en, name_da) VALUES('CV', 'Cape Verde', 'Kap Verde');
INSERT INTO countries (code, name_en, name_da) VALUES('BQ', 'Caribbean Netherlands', 'De tidligere Nederlandske Antiller');
INSERT INTO countries (code, name_en, name_da) VALUES('KY', 'Cayman Islands', 'Caymanøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('CF', 'Central African Republic', 'Den Centralafrikanske Republik');
INSERT INTO countries (code, name_en, name_da) VALUES('EA', 'Ceuta & Melilla', 'Ceuta og Melilla');
INSERT INTO countries (code, name_en, name_da) VALUES('TD', 'Chad', 'Tchad');
INSERT INTO countries (code, name_en, name_da) VALUES('CL', 'Chile', 'Chile');
INSERT INTO countries (code, name_en, name_da) VALUES('CN', 'China', 'Kina');
INSERT INTO countries (code, name_en, name_da) VALUES('CX', 'Christmas Island', 'Juleøen');
INSERT INTO countries (code, name_en, name_da) VALUES('CC', 'Cocos (Keeling) Islands', 'Cocosøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('CO', 'Colombia', 'Colombia');
INSERT INTO countries (code, name_en, name_da) VALUES('KM', 'Comoros', 'Comorerne');
INSERT INTO countries (code, name_en, name_da) VALUES('CG', 'Congo - Brazzaville', 'Congo-Brazzaville');
INSERT INTO countries (code, name_en, name_da) VALUES('CD', 'Congo - Kinshasa', 'Congo-Kinshasa');
INSERT INTO countries (code, name_en, name_da) VALUES('CK', 'Cook Islands', 'Cookøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('CR', 'Costa Rica', 'Costa Rica');
INSERT INTO countries (code, name_en, name_da) VALUES('HR', 'Croatia', 'Kroatien');
INSERT INTO countries (code, name_en, name_da) VALUES('CU', 'Cuba', 'Cuba');
INSERT INTO countries (code, name_en, name_da) VALUES('CW', 'Curaçao', 'Curaçao');
INSERT INTO countries (code, name_en, name_da) VALUES('CY', 'Cyprus', 'Cypern');
INSERT INTO countries (code, name_en, name_da) VALUES('CZ', 'Czechia', 'Tjekkiet');
INSERT INTO countries (code, name_en, name_da) VALUES('CI', 'Côte d’Ivoire', 'Elfenbenskysten');
INSERT INTO countries (code, name_en, name_da) VALUES('DK', 'Denmark', 'Danmark');
INSERT INTO countries (code, name_en, name_da) VALUES('DG', 'Diego Garcia', 'Diego Garcia');
INSERT INTO countries (code, name_en, name_da) VALUES('DJ', 'Djibouti', 'Djibouti');
INSERT INTO countries (code, name_en, name_da) VALUES('DM', 'Dominica', 'Dominica');
INSERT INTO countries (code, name_en, name_da) VALUES('DO', 'Dominican Republic', 'Den Dominikanske Republik');
INSERT INTO countries (code, name_en, name_da) VALUES('EC', 'Ecuador', 'Ecuador');
INSERT INTO countries (code, name_en, name_da) VALUES('EG', 'Egypt', 'Egypten');
INSERT INTO countries (code, name_en, name_da) VALUES('SV', 'El Salvador', 'El Salvador');
INSERT INTO countries (code, name_en, name_da) VALUES('GQ', 'Equatorial Guinea', 'Ækvatorialguinea');
INSERT INTO countries (code, name_en, name_da) VALUES('ER', 'Eritrea', 'Eritrea');
INSERT INTO countries (code, name_en, name_da) VALUES('EE', 'Estonia', 'Estland');
INSERT INTO countries (code, name_en, name_da) VALUES('SZ', 'Eswatini', 'Eswatini');
INSERT INTO countries (code, name_en, name_da) VALUES('ET', 'Ethiopia', 'Etiopien');
INSERT INTO countries (code, name_en, name_da) VALUES('FK', 'Falkland Islands', 'Falklandsøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('FO', 'Faroe Islands', 'Færøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('FJ', 'Fiji', 'Fiji');
INSERT INTO countries (code, name_en, name_da) VALUES('FI', 'Finland', 'Finland');
INSERT INTO countries (code, name_en, name_da) VALUES('FR', 'France', 'Frankrig');
INSERT INTO countries (code, name_en, name_da) VALUES('GF', 'French Guiana', 'Fransk Guyana');
INSERT INTO countries (code, name_en, name_da) VALUES('PF', 'French Polynesia', 'Fransk Polynesien');
INSERT INTO countries (code, name_en, name_da) VALUES('GA', 'Gabon', 'Gabon');
INSERT INTO countries (code, name_en, name_da) VALUES('GM', 'Gambia', 'Gambia');
INSERT INTO countries (code, name_en, name_da) VALUES('GE', 'Georgia', 'Georgien');
INSERT INTO countries (code, name_en, name_da) VALUES('DE', 'Germany', 'Tyskland');
INSERT INTO countries (code, name_en, name_da) VALUES('GH', 'Ghana', 'Ghana');
INSERT INTO countries (code, name_en, name_da) VALUES('GI', 'Gibraltar', 'Gibraltar');
INSERT INTO countries (code, name_en, name_da) VALUES('GR', 'Greece', 'Grækenland');
INSERT INTO countries (code, name_en, name_da) VALUES('GL', 'Greenland', 'Grønland');
INSERT INTO countries (code, name_en, name_da) VALUES('GD', 'Grenada', 'Grenada');
INSERT INTO countries (code, name_en, name_da) VALUES('GP', 'Guadeloupe', 'Guadeloupe');
INSERT INTO countries (code, name_en, name_da) VALUES('GU', 'Guam', 'Guam');
INSERT INTO countries (code, name_en, name_da) VALUES('GT', 'Guatemala', 'Guatemala');
INSERT INTO countries (code, name_en, name_da) VALUES('GG', 'Guernsey', 'Guernsey');
INSERT INTO countries (code, name_en, name_da) VALUES('GN', 'Guinea', 'Guinea');
INSERT INTO countries (code, name_en, name_da) VALUES('GW', 'Guinea-Bissau', 'Guinea-Bissau');
INSERT INTO countries (code, name_en, name_da) VALUES('GY', 'Guyana', 'Guyana');
INSERT INTO countries (code, name_en, name_da) VALUES('HT', 'Haiti', 'Haiti');
INSERT INTO countries (code, name_en, name_da) VALUES('HN', 'Honduras', 'Honduras');
INSERT INTO countries (code, name_en, name_da) VALUES('HK', 'Hong Kong SAR China', 'SAR Hongkong');
INSERT INTO countries (code, name_en, name_da) VALUES('HU', 'Hungary', 'Ungarn');
INSERT INTO countries (code, name_en, name_da) VALUES('IS', 'Iceland', 'Island');
INSERT INTO countries (code, name_en, name_da) VALUES('IN', 'India', 'Indien');
INSERT INTO countries (code, name_en, name_da) VALUES('ID', 'Indonesia', 'Indonesien');
INSERT INTO countries (code, name_en, name_da) VALUES('IR', 'Iran', 'Iran');
INSERT INTO countries (code, name_en, name_da) VALUES('IQ', 'Iraq', 'Irak');
INSERT INTO countries (code, name_en, name_da) VALUES('IE', 'Ireland', 'Irland');
INSERT INTO countries (code, name_en, name_da) VALUES('IM', 'Isle of Man', 'Isle of Man');
INSERT INTO countries (code, name_en, name_da) VALUES('IL', 'Israel', 'Israel');
INSERT INTO countries (code, name_en, name_da) VALUES('IT', 'Italy', 'Italien');
INSERT INTO countries (code, name_en, name_da) VALUES('JM', 'Jamaica', 'Jamaica');
INSERT INTO countries (code, name_en, name_da) VALUES('JP', 'Japan', 'Japan');
INSERT INTO countries (code, name_en, name_da) VALUES('JE', 'Jersey', 'Jersey');
INSERT INTO countries (code, name_en, name_da) VALUES('JO', 'Jordan', 'Jordan');
INSERT INTO countries (code, name_en, name_da) VALUES('KZ', 'Kazakhstan', 'Kasakhstan');
INSERT INTO countries (code, name_en, name_da) VALUES('KE', 'Kenya', 'Kenya');
INSERT INTO countries (code, name_en, name_da) VALUES('KI', 'Kiribati', 'Kiribati');
INSERT INTO countries (code, name_en, name_da) VALUES('XK', 'Kosovo', 'Kosovo');
INSERT INTO countries (code, name_en, name_da) VALUES('KW', 'Kuwait', 'Kuwait');
INSERT INTO countries (code, name_en, name_da) VALUES('KG', 'Kyrgyzstan', 'Kirgisistan');
INSERT INTO countries (code, name_en, name_da) VALUES('LA', 'Laos', 'Laos');
INSERT INTO countries (code, name_en, name_da) VALUES('LV', 'Latvia', 'Letland');
INSERT INTO countries (code, name_en, name_da) VALUES('LB', 'Lebanon', 'Libanon');
INSERT INTO countries (code, name_en, name_da) VALUES('LS', 'Lesotho', 'Lesotho');
INSERT INTO countries (code, name_en, name_da) VALUES('LR', 'Liberia', 'Liberia');
INSERT INTO countries (code, name_en, name_da) VALUES('LY', 'Libya', 'Libyen');
INSERT INTO countries (code, name_en, name_da) VALUES('LI', 'Liechtenstein', 'Liechtenstein');
INSERT INTO countries (code, name_en, name_da) VALUES('LT', 'Lithuania', 'Litauen');
INSERT INTO countries (code, name_en, name_da) VALUES('LU', 'Luxembourg', 'Luxembourg');
INSERT INTO countries (code, name_en, name_da) VALUES('MO', 'Macao SAR China', 'SAR Macao');
INSERT INTO countries (code, name_en, name_da) VALUES('MG', 'Madagascar', 'Madagaskar');
INSERT INTO countries (code, name_en, name_da) VALUES('MW', 'Malawi', 'Malawi');
INSERT INTO countries (code, name_en, name_da) VALUES('MY', 'Malaysia', 'Malaysia');
INSERT INTO countries (code, name_en, name_da) VALUES('ML', 'Mali', 'Mali');
INSERT INTO countries (code, name_en, name_da) VALUES('MT', 'Malta', 'Malta');
INSERT INTO countries (code, name_en, name_da) VALUES('MH', 'Marshall Islands', 'Marshalløerne');
INSERT INTO countries (code, name_en, name_da) VALUES('MQ', 'Martinique', 'Martinique');
INSERT INTO countries (code, name_en, name_da) VALUES('MR', 'Mauritania', 'Mauretanien');
INSERT INTO countries (code, name_en, name_da) VALUES('MU', 'Mauritius', 'Mauritius');
INSERT INTO countries (code, name_en, name_da) VALUES('YT', 'Mayotte', 'Mayotte');
INSERT INTO countries (code, name_en, name_da) VALUES('MX', 'Mexico', 'Mexico');
INSERT INTO countries (code, name_en, name_da) VALUES('FM', 'Micronesia', 'Mikronesien');
INSERT INTO countries (code, name_en, name_da) VALUES('MD', 'Moldova', 'Moldova');
INSERT INTO countries (code, name_en, name_da) VALUES('MC', 'Monaco', 'Monaco');
INSERT INTO countries (code, name_en, name_da) VALUES('MN', 'Mongolia', 'Mongoliet');
INSERT INTO countries (code, name_en, name_da) VALUES('ME', 'Montenegro', 'Montenegro');
INSERT INTO countries (code, name_en, name_da) VALUES('MS', 'Montserrat', 'Montserrat');
INSERT INTO countries (code, name_en, name_da) VALUES('MA', 'Morocco', 'Marokko');
INSERT INTO countries (code, name_en, name_da) VALUES('MZ', 'Mozambique', 'Mozambique');
INSERT INTO countries (code, name_en, name_da) VALUES('MM', 'Myanmar (Burma)', 'Myanmar (Burma)');
INSERT INTO countries (code, name_en, name_da) VALUES('NA', 'Namibia', 'Namibia');
INSERT INTO countries (code, name_en, name_da) VALUES('NR', 'Nauru', 'Nauru');
INSERT INTO countries (code, name_en, name_da) VALUES('NP', 'Nepal', 'Nepal');
INSERT INTO countries (code, name_en, name_da) VALUES('NL', 'Netherlands', 'Holland');
INSERT INTO countries (code, name_en, name_da) VALUES('NC', 'New Caledonia', 'Ny Kaledonien');
INSERT INTO countries (code, name_en, name_da) VALUES('NZ', 'New Zealand', 'New Zealand');
INSERT INTO countries (code, name_en, name_da) VALUES('NI', 'Nicaragua', 'Nicaragua');
INSERT INTO countries (code, name_en, name_da) VALUES('NE', 'Niger', 'Niger');
INSERT INTO countries (code, name_en, name_da) VALUES('NG', 'Nigeria', 'Nigeria');
INSERT INTO countries (code, name_en, name_da) VALUES('NU', 'Niue', 'Niue');
INSERT INTO countries (code, name_en, name_da) VALUES('NF', 'Norfolk Island', 'Norfolk Island');
INSERT INTO countries (code, name_en, name_da) VALUES('KP', 'North Korea', 'Nordkorea');
INSERT INTO countries (code, name_en, name_da) VALUES('MK', 'North Macedonia', 'Nordmakedonien');
INSERT INTO countries (code, name_en, name_da) VALUES('MP', 'Northern Mariana Islands', 'Nordmarianerne');
INSERT INTO countries (code, name_en, name_da) VALUES('NO', 'Norway', 'Norge');
INSERT INTO countries (code, name_en, name_da) VALUES('OM', 'Oman', 'Oman');
INSERT INTO countries (code, name_en, name_da) VALUES('PK', 'Pakistan', 'Pakistan');
INSERT INTO countries (code, name_en, name_da) VALUES('PW', 'Palau', 'Palau');
INSERT INTO countries (code, name_en, name_da) VALUES('PS', 'Palestinian Territories', 'De palæstinensiske områder');
INSERT INTO countries (code, name_en, name_da) VALUES('PA', 'Panama', 'Panama');
INSERT INTO countries (code, name_en, name_da) VALUES('PG', 'Papua New Guinea', 'Papua Ny Guinea');
INSERT INTO countries (code, name_en, name_da) VALUES('PY', 'Paraguay', 'Paraguay');
INSERT INTO countries (code, name_en, name_da) VALUES('PE', 'Peru', 'Peru');
INSERT INTO countries (code, name_en, name_da) VALUES('PH', 'Philippines', 'Filippinerne');
INSERT INTO countries (code, name_en, name_da) VALUES('PN', 'Pitcairn Islands', 'Pitcairn');
INSERT INTO countries (code, name_en, name_da) VALUES('PL', 'Poland', 'Polen');
INSERT INTO countries (code, name_en, name_da) VALUES('PT', 'Portugal', 'Portugal');
INSERT INTO countries (code, name_en, name_da) VALUES('PR', 'Puerto Rico', 'Puerto Rico');
INSERT INTO countries (code, name_en, name_da) VALUES('QA', 'Qatar', 'Qatar');
INSERT INTO countries (code, name_en, name_da) VALUES('RO', 'Romania', 'Rumænien');
INSERT INTO countries (code, name_en, name_da) VALUES('RU', 'Russia', 'Rusland');
INSERT INTO countries (code, name_en, name_da) VALUES('RW', 'Rwanda', 'Rwanda');
INSERT INTO countries (code, name_en, name_da) VALUES('RE', 'Réunion', 'Réunion');
INSERT INTO countries (code, name_en, name_da) VALUES('WS', 'Samoa', 'Samoa');
INSERT INTO countries (code, name_en, name_da) VALUES('SM', 'San Marino', 'San Marino');
INSERT INTO countries (code, name_en, name_da) VALUES('SA', 'Saudi Arabia', 'Saudi-Arabien');
INSERT INTO countries (code, name_en, name_da) VALUES('SN', 'Senegal', 'Senegal');
INSERT INTO countries (code, name_en, name_da) VALUES('RS', 'Serbia', 'Serbien');
INSERT INTO countries (code, name_en, name_da) VALUES('SC', 'Seychelles', 'Seychellerne');
INSERT INTO countries (code, name_en, name_da) VALUES('SL', 'Sierra Leone', 'Sierra Leone');
INSERT INTO countries (code, name_en, name_da) VALUES('SG', 'Singapore', 'Singapore');
INSERT INTO countries (code, name_en, name_da) VALUES('SX', 'Sint Maarten', 'Sint Maarten');
INSERT INTO countries (code, name_en, name_da) VALUES('SK', 'Slovakia', 'Slovakiet');
INSERT INTO countries (code, name_en, name_da) VALUES('SI', 'Slovenia', 'Slovenien');
INSERT INTO countries (code, name_en, name_da) VALUES('SB', 'Solomon Islands', 'Salomonøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('SO', 'Somalia', 'Somalia');
INSERT INTO countries (code, name_en, name_da) VALUES('ZA', 'South Africa', 'Sydafrika');
INSERT INTO countries (code, name_en, name_da) VALUES('KR', 'South Korea', 'Sydkorea');
INSERT INTO countries (code, name_en, name_da) VALUES('SS', 'South Sudan', 'Sydsudan');
INSERT INTO countries (code, name_en, name_da) VALUES('ES', 'Spain', 'Spanien');
INSERT INTO countries (code, name_en, name_da) VALUES('LK', 'Sri Lanka', 'Sri Lanka');
INSERT INTO countries (code, name_en, name_da) VALUES('BL', 'St. Barthélemy', 'Saint Barthélemy');
INSERT INTO countries (code, name_en, name_da) VALUES('SH', 'St. Helena', 'St. Helena');
INSERT INTO countries (code, name_en, name_da) VALUES('KN', 'St. Kitts & Nevis', 'Saint Kitts og Nevis');
INSERT INTO countries (code, name_en, name_da) VALUES('LC', 'St. Lucia', 'Saint Lucia');
INSERT INTO countries (code, name_en, name_da) VALUES('MF', 'St. Martin', 'Saint Martin');
INSERT INTO countries (code, name_en, name_da) VALUES('PM', 'St. Pierre & Miquelon', 'Saint Pierre og Miquelon');
INSERT INTO countries (code, name_en, name_da) VALUES('VC', 'St. Vincent & Grenadines', 'Saint Vincent og Grenadinerne');
INSERT INTO countries (code, name_en, name_da) VALUES('SD', 'Sudan', 'Sudan');
INSERT INTO countries (code, name_en, name_da) VALUES('SR', 'Suriname', 'Surinam');
INSERT INTO countries (code, name_en, name_da) VALUES('SJ', 'Svalbard & Jan Mayen', 'Svalbard og Jan Mayen');
INSERT INTO countries (code, name_en, name_da) VALUES('SE', 'Sweden', 'Sverige');
INSERT INTO countries (code, name_en, name_da) VALUES('CH', 'Switzerland', 'Schweiz');
INSERT INTO countries (code, name_en, name_da) VALUES('SY', 'Syria', 'Syrien');
INSERT INTO countries (code, name_en, name_da) VALUES('ST', 'São Tomé & Príncipe', 'São Tomé og Príncipe');
INSERT INTO countries (code, name_en, name_da) VALUES('TW', 'Taiwan', 'Taiwan');
INSERT INTO countries (code, name_en, name_da) VALUES('TJ', 'Tajikistan', 'Tadsjikistan');
INSERT INTO countries (code, name_en, name_da) VALUES('TZ', 'Tanzania', 'Tanzania');
INSERT INTO countries (code, name_en, name_da) VALUES('TH', 'Thailand', 'Thailand');
INSERT INTO countries (code, name_en, name_da) VALUES('TL', 'Timor-Leste', 'Timor-Leste');
INSERT INTO countries (code, name_en, name_da) VALUES('TG', 'Togo', 'Togo');
INSERT INTO countries (code, name_en, name_da) VALUES('TK', 'Tokelau', 'Tokelau');
INSERT INTO countries (code, name_en, name_da) VALUES('TO', 'Tonga', 'Tonga');
INSERT INTO countries (code, name_en, name_da) VALUES('TT', 'Trinidad & Tobago', 'Trinidad og Tobago');
INSERT INTO countries (code, name_en, name_da) VALUES('TN', 'Tunisia', 'Tunesien');
INSERT INTO countries (code, name_en, name_da) VALUES('TR', 'Turkey', 'Tyrkiet');
INSERT INTO countries (code, name_en, name_da) VALUES('TM', 'Turkmenistan', 'Turkmenistan');
INSERT INTO countries (code, name_en, name_da) VALUES('TC', 'Turks & Caicos Islands', 'Turks- og Caicosøerne');
INSERT INTO countries (code, name_en, name_da) VALUES('TV', 'Tuvalu', 'Tuvalu');
INSERT INTO countries (code, name_en, name_da) VALUES('UM', 'U.S. Outlying Islands', 'Amerikanske oversøiske øer');
INSERT INTO countries (code, name_en, name_da) VALUES('VI', 'U.S. Virgin Islands', 'De Amerikanske Jomfruøer');
INSERT INTO countries (code, name_en, name_da) VALUES('UG', 'Uganda', 'Uganda');
INSERT INTO countries (code, name_en, name_da) VALUES('UA', 'Ukraine', 'Ukraine');
INSERT INTO countries (code, name_en, name_da) VALUES('AE', 'United Arab Emirates', 'De Forenede Arabiske Emirater');
INSERT INTO countries (code, name_en, name_da) VALUES('GB', 'United Kingdom', 'Storbritannien');
INSERT INTO countries (code, name_en, name_da) VALUES('US', 'United States', 'USA');
INSERT INTO countries (code, name_en, name_da) VALUES('UY', 'Uruguay', 'Uruguay');
INSERT INTO countries (code, name_en, name_da) VALUES('UZ', 'Uzbekistan', 'Usbekistan');
INSERT INTO countries (code, name_en, name_da) VALUES('VU', 'Vanuatu', 'Vanuatu');
INSERT INTO countries (code, name_en, name_da) VALUES('VA', 'Vatican City', 'Vatikanstaten');
INSERT INTO countries (code, name_en, name_da) VALUES('VE', 'Venezuela', 'Venezuela');
INSERT INTO countries (code, name_en, name_da) VALUES('VN', 'Vietnam', 'Vietnam');
INSERT INTO countries (code, name_en, name_da) VALUES('WF', 'Wallis & Futuna', 'Wallis og Futuna');
INSERT INTO countries (code, name_en, name_da) VALUES('EH', 'Western Sahara', 'Vestsahara');
INSERT INTO countries (code, name_en, name_da) VALUES('YE', 'Yemen', 'Yemen');
INSERT INTO countries (code, name_en, name_da) VALUES('ZM', 'Zambia', 'Zambia');
INSERT INTO countries (code, name_en, name_da) VALUES('ZW', 'Zimbabwe', 'Zimbabwe');
INSERT INTO countries (code, name_en, name_da) VALUES('AX', 'Åland Islands', 'Åland');

ALTER TABLE deltagere DROP COLUMN land;
ALTER TABLE deltagere ADD country CHAR(2) NOT NULL DEFAULT 'DK';
ALTER TABLE deltagere ADD CONSTRAINT `deltagere_ibfk_4` FOREIGN KEY (`country`) REFERENCES `countries` (`code`);
