<p>Hej <?= e($this->participant->fornavn);?>,</p>

<p>
  Du er en af dem, der skal have et billede på dit navneskilt til Fastaval - fordi du er arrangør, forfatter, designer
  eller lign.
</p>

<p>
  Du har tilsyneladende ikke uploadet et billede til dit navneskilt endnu. Uden billede kan du ikke bruge dit navneskilt
  til at få rabat. Så derfor minder vi dig lige om at du skal uploade et billede senest 
  <strong><?=$this->signup_end_time?></strong> - og det kan du gøre på følgende link:
</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>
  Hvis du allerede har forsøgt at uploade et billede men systemet ikke har givet dig lov, så beklager vi meget.
  Kontakt gerne <a href="mailto:info@fastaval.dk">info@fastaval.dk</a> og lad os vide der er et problem - og send gerne
  dit billede med.
</p>

<p>
  Venlige hilsner<br/>
  Fastaval
</p>
