<p>Hej <?= e($this->participant->fornavn);?>,</p>

<p>Du er en af dem, der skal have et ID-kort til Fastaval - fordi du er arrangør, forfatter, designer eller lign.</p>

<p>MEN ... du har tilsyneladende ikke uploadet et billede til dit kort. Og intet billede, intet kort. Så derfor minder vi dig lige om at du skal uploade et billede - og det kan du gøre på følgende link:</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>Hvis du allerede har forsøgt at uploade et billede men systemet ikke har givet dig lov, så beklager vi meget. Kontakt gerne <a href="mailto:info@fastaval.dk">info@fastaval.dk</a> og lad os vide der er et problem - og send gerne dit billede med.</p>

<p>Venlige hilsner<br/>
Fastaval</p>
