<form action="<?= $this->url('sms_auto_dryrun');?>" method="post">
    <p><label for="when">When</label><input type="text" class="datetimepicker" name="when" id="when"/></p>

    <button class="btn btn-primary">Dry-run</button>
</form>
<?php if ($this->dryrun_results) { ?>
<hr/>
<p><?= e($this->when);?></p>
<p>Messages: <?= count($this->dryrun_results);?></p>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Number</th>
            <th>Message</th>
            <th>URL</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->dryrun_results as $result) : ?>
        <tr>
            <td><?= e($result['participant']->id);?></td>
            <td><?= e($result['number']);?></td>
            <td><?= e($result['message']);?></td>
            <td><?= e($result['url']);?></td>
        </tr>
<?php endforeach;?>
    </tbody>
</table>
<?php } ?>
