<div id='food-details'>
  <fieldset>
    <legend><?php echo (isset($this->mad) ? 'Opdater' : 'Opret');?> mad-kategori</legend>
    <form action='' method='post'>
      <input id='mad-id' type='hidden' value='<?php echo $this->id;?>'/>
      <span class='label'>Kategori:</span> <span class='detail'><input type='text' name='kategori' value='<?php echo (isset($this->mad) ? $this->mad->kategori : '');?>'/></span><br/>
      <span class='label'>Pris:</span> <span class='detail'><input type='text' name='pris' value='<?php echo (isset($this->mad) ? $this->mad->pris : '');?>'/></span><br/>
      <hr/>
      <b>Mad tider:</b>
      <?php if (isset($this->mad)) : foreach ($this->mad->getMadTider() as $tid) : ?>
      <table>
        <tbody>
          <tr>
            <td><span class='label'>Dato:</span></td>
            <td>
              <input name='foodtime_id[]' value='<?=$tid->id?>' type='hidden'/>
              <input type='text' value='<?=$tid->dato?>' name='foodtime_date[]'/>
            </td>
          </tr>
          <tr>
            <td><span class='label'>Beskrivelse:</span></td>
            <td><input type='text' value='<?=$tid->description_da?>' name='foodtime_desc_da[]'/></td>
          </tr>
          <tr>
            <td><span class='label'>Engelsk:</span></td>
            <td><input type='text' value='<?=$tid->description_en?>' name='foodtime_desc_en[]'/></td>
          </tr>
          <tr>
            <td><input type='button' value='Slet' class='remove-foodtime' /></td>
          </tr>
        </tbody>
      </table>
      <?php endforeach; endif;?>
      <input type='button' value='Tilføj' id='add-foodtime' />
      <hr/>
      <?php if (isset($this->mad)):?>
        <input type='submit' value='Opdater' name='update_food' class='centersubmits'/>
        <input type='submit' value='Fortryd' class='centersubmits'/>
        <input type='submit' value='Slet' name='delete_food' class='centersubmits'/>
      <?php else:?>
        <input type='submit' value='Opret' name='create_food'/>
      <?php endif;?>
    </form>
  </fieldset>
</div>
<script type='text/javascript' src="<?php echo $this->JSLink('food.js');?>"></script>
