<div class="votingModule">
    <form action="<?= $this->url('cast_vote');?>" method="POST">
        <h3>You are voting for / Du stemmer på</h3>
        <h2><?= e($this->activity->navn);?> / <?= e($this->activity->title_en);?></h2>
        <input type="hidden" value="<?= e($this->vote['id']);?>" name="id"/>
        <button type="submit" class="btn btn-important">Vote! | Stem!</button>
    </form>
</div>
