<div class='middleboxes'>
    <div id='aktivitetbox'>
        <form method='post' action='' id='aktivitet-edit'>
        <fieldset>
            <legend>Opdater Aktivitet</legend>
            <table>
                <tr>
                    <td><strong>Id:</strong> <?= $this->aktivitet->id;?></td>
                </tr>
                <tr>
                    <td><strong>Titel:</strong></td>
                    <td colspan="5"><input name='aktivitet[navn]' class='aktivitet-title' value='<?= e($this->aktivitet->navn);?>' type='text' /></td>
                </tr>
                <tr>
                    <td><strong>Engelsk titel:</strong></td>
                    <td colspan="5"><input name='aktivitet[title_en]' class='aktivitet-title' value='<?= e($this->aktivitet->title_en);?>' type='text' /></td>
                </tr>
                <tr>
                    <td><strong>Forfatter(e):</strong></td>
                    <td colspan="5"><input class="aktivitet-title" name="aktivitet[author]" type="text" value="<?= e($this->aktivitet->author);?>"/></td>
                </tr>
                <tr>
                    <td><strong>WP id:</strong></td>
                    <td><input name='aktivitet[wp_link]' type='number' value='<?= $this->aktivitet->wp_link;?>'/></td>
                    <td><strong>Spiltype:</strong></td>
                    <td><?= $this->genSelect('aktivitet[type]', $this->model->getActivityTypes(), $this->aktivitet->type);?></td>
                    <td><strong>Varighed:</strong></td>
                    <td><input name='aktivitet[varighed_per_afvikling]' type='number' value='<?= e($this->aktivitet->varighed_per_afvikling);?>' /></td>
                </tr>
                <tr>
                    <td><strong>Min Spillere:</strong></td>
                    <td><input name='aktivitet[min_deltagere_per_hold]' type='number' value='<?= e($this->aktivitet->min_deltagere_per_hold);?>' /></td>
                    <td><strong>Max Spillere:</strong></td>
                    <td><input name='aktivitet[max_deltagere_per_hold]' type='number' value='<?= e($this->aktivitet->max_deltagere_per_hold);?>' /></td>
                    <td><strong>Spilledere:</strong></td>
                    <td><input name='aktivitet[spilledere_per_hold]' type='number' value='<?= e($this->aktivitet->spilledere_per_hold);?>' /></td>
                </tr>
                <tr>
                    <td><strong>Pris:</strong></td>
                    <td><input name='aktivitet[pris]' type='number' value='<?= e($this->aktivitet->pris);?>' /></td>
                    <td><strong>Kan tilmeldes:</strong></td>
                    <td><?= $this->genSelect('aktivitet[kan_tilmeldes]', array('ja', 'nej'), $this->aktivitet->kan_tilmeldes);?></td>
                    <td><strong>Fylder lokale:</strong></td>
                    <td><?= $this->genSelect('aktivitet[lokale_eksklusiv]', array('ja', 'nej'), $this->aktivitet->lokale_eksklusiv);?></td>
                </tr>
                <tr>
                    <td colspan='4'>
                        <strong>Sprog:</strong>
                        <label><input type='radio' name='aktivitet[sprog]' value='dansk' <?= ($this->aktivitet->sprog == 'dansk' ? "checked='checked'" : '');?>> dansk</label>
                        <label><input type='radio' name='aktivitet[sprog]' value='engelsk' <?= ($this->aktivitet->sprog == 'engelsk' ? "checked='checked'" : '');?>> engelsk</label>
                        <label><input type='radio' name='aktivitet[sprog]' value='dansk+engelsk' <?= ($this->aktivitet->sprog == 'dansk+engelsk' ? "checked='checked'" : '');?>> dansk, med mulighed for engelsk</label>
                    </td>
                    <td><strong>Udelukker samtidige aktiviteter:</strong></td>
                    <td><?= $this->genSelect('aktivitet[tids_eksklusiv]', array('ja', 'nej'), $this->aktivitet->tids_eksklusiv);?></td>
                </tr>
                <tr>
                    <td><strong>Kan spilles flere gange:</strong></td>
                    <td><?= $this->genSelect('aktivitet[replayable]', array('ja', 'nej'), $this->aktivitet->replayable);?></td>
                    <td><strong>Skjult:</strong></td>
                    <td><?= $this->genSelect('aktivitet[hidden]', array('ja', 'nej'), $this->aktivitet->hidden);?></td>
                    <td><strong>Karmatype:</strong></td>
                    <td>
                        <select name="aktivitet[karmatype]">
                            <option value="0">Ingen</option>
                            <option value="<?= KARMATYPE_SMALL;?>" <?= intval($this->aktivitet->karmatype) === KARMATYPE_SMALL ? 'selected="selected"' : '';?>>Lille</option>
                            <option value="<?= KARMATYPE_MEDIUM;?>" <?= intval($this->aktivitet->karmatype) === KARMATYPE_MEDIUM ? 'selected="selected"' : '';?>>Medium</option>
                            <option value="<?= KARMATYPE_BIG;?>" <?= intval($this->aktivitet->karmatype) === KARMATYPE_BIG ? 'selected="selected"' : '';?>>Stor</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><strong>Minimum Alder:</strong></td>
                    <td><input type="number" min="0" max="200" name="min_age" size="4" step="1" value="<?= e($this->aktivitet->getMinAge());?>"/></td>
                    <td><strong>Maksimum Alder:</strong></td>
                    <td><input type="number" min="0" max="200" size="4" name="max_age" step="1" value="<?= e($this->aktivitet->getMaxAge());?>"/></td>
                    <td><strong>Max tilmeldinger</strong></td>
                    <td><input type="number" min="0" max="1000" step="1" value="<?= e($this->aktivitet->max_signups);?>" name="aktivitet[max_signups]"/></td>
                </tr>
                <tr>
                    <td><strong>Automatisk tilmelding:</strong></td>
                    <td><?=$this->genSelect('aktivitet[auto_signup_category]', $this->model->getAutoRegisterCategories(), $this->aktivitet->auto_signup_category)?></td>
                </tr>
                <tr>
                    <td><strong>Note:</strong></td>
                </tr>
                <tr>
                    <td colspan='6'><textarea name='aktivitet[note]'><?= (isset($this->aktivitet->note) ? e($this->aktivitet->note) : "");?></textarea></td>
                </tr>
                <tr>
                    <td><strong>Foromtale:</strong></td>
                </tr>
                <tr>
                    <td colspan='6'><textarea name='aktivitet[foromtale]'><?= (isset($this->aktivitet->foromtale) ? e($this->aktivitet->foromtale) : "") ;?></textarea></td>
                </tr>
                <tr>
                    <td><strong>Engelsk foromtale:</strong></td>
                </tr>
                <tr>
                    <td colspan='6'><textarea name='aktivitet[description_en]'><?= (isset($this->aktivitet->description_en) ? e($this->aktivitet->description_en) : "") ;?></textarea></td>
                </tr>
            </table>
            <input type='submit' value='Opdater' class='centersubmits' name='update_activity' />
            <input type='submit' value='Fortryd' class='centersubmits' name='fortryd' />
            <input type='submit' value='Slet' class='centersubmits' name='slet_aktivitet' />
        </fieldset>
        </form>
    </div>
</div>
