<?=$this->getMessagesHtml()?>
<div class='middleboxes'>
	<fieldset>
		<legend>Importer Aktiviteter</legend>
		<div class="outer-container">
			<p>Bemærk det er vigtigt at kolonner står i den rigtige rækkefølge.</p>
			<p>Man vil kunne se resultatet af importen inden man vælger at lægge det i databasen</p>
			<form action="" method="post" name="frmExcelImport" id="frmExcelImport" enctype="multipart/form-data">
				<div>
					<label>Vælg Excel Fil</label>
					<input type="file" name="activities" id="activities_file" accept=".xls,.xlsx">
					<button type="submit" id="importactivities" name="importactivities" class="btn-submit">Importér</button>
				</div>
			</form>
		</div>
	</fieldset>
	<?php 
	if (isset($this->activity_data)) { ?>
		<fieldset>
			<p>Herunder kan du se de data infosys har læst fra arket</p>
			<p>Vil du overskrive de aktiviteter der allerede ligger i databasen?
			<br>Eller vil du tilføje alle disse aktiviteter til dem der ligger i forvejen?
			<br>(Infosys checker ikke om du tilføjer en aktivitet der ellerede findes i forvejen, det skal du selv gøre)</p>
			<form action="" method="post" name="frmConfirmImport" id="frmConfirmImport" enctype="multipart/form-data">
				<button type="submit" id="import_add" name="import_add" class="btn-submit">Tilføj</button>
				<button type="submit" id="import_replace" name="import_replace" class="btn-submit">Overskriv</button>
			</form>
			<table class="importTable">
				<tr>
					<?php foreach($this->activity_header as $header) { ?>
							<th><?=$header?></th>
					<?php } ?>
				</tr>
				<?php foreach($this->activity_data as $row){ ?>
					<tr>
						<?php foreach($row as $key => $cell) { 
							if($key == "updated") {
								$cell = preg_replace("/ /","&nbsp;",$cell);
								$cell = preg_replace("/-/","&#8209;",$cell);
							} ?>
							<td><?=$cell?></td>
						<?php } ?>
					</tr>
				<?php } ?>
			</table>
		</fieldset>
	<?php } ?>
</div>