<div>
    <form action='' method='post'>
        <fieldset>
            <legend>Opret Hold</legend>
            <div>
                <select id='aktivitet_navn' name='aktivitet_navn'>
                    <option value=''>Vælg</option>
                    <?php foreach ($this->aktiviteter as $aktivitet) : ?>
                        <option value='<?php echo e($aktivitet->id);?>'><?php echo e($aktivitet->navn);?></option>
                    <?php endforeach;?>
                </select>
                <select id='aktivitet_tid' name='afvikling_id'>
                </select>
                <select id='lokale' name='lokale_id'>
                </select>
            </div>
            <input name='hold_opret' value='Opret' type='submit' />
        </fieldset>
    </form>
</div>
<script src="<?php echo $this->JSLink('imwedit.js');?>" type='text/javascript'></script>
<script type='text/javascript'>
madwearedit.public_uri = '<?php echo $this->public_uri;?>';
madwearedit.setupHold();
</script>
