<?php echo $this->getMessagesHtml();?>
<div>
<h3>Liste over <?=$this->headname?> bestillinger</h3>
    <?php foreach ($this->orders as $ord) : ?>
    <div class='deltager-wearorder'>
        <?php
            $deltager = $ord->getDeltager();
        ?>
        <p class='deltager-wearorder-deltager'>
            ID: <?=$deltager->id?>
            Navn: <a href="<?=$this->url('visdeltager', array('id' => $deltager->id))?>"><?=$deltager->fornavn?> <?=$deltager->efternavn?></a>
        </p>
        <p class='deltager-wearord-order'>
            Kategori: <?=$ord->getWearName('da', false)?>, <?=$ord->getWearpris()->getCategory()->navn?>
            Antal: <?=$ord->antal?>
            <?php if($ord->size !== null) { ?>
                Str.: <?=$ord->getSizeName()?>
            <?php } ?>
        </p>
    </div>
    <?php endforeach; ?>
</div>
