<?php echo $this->getMessagesHtml();?>
<p>Du kan:
    <ul>
        <li><a href="<?php echo $this->url('wear_breakdown');?>">se oversigt over bestilt wear</a>.</li>
        <li><a href="<?php echo $this->url('detailed_order_list');?>">se alle wear-bestillinger</a>.</li>
        <li><a href="<?php echo $this->url('detailed_order_list');?>">se alle ikke-udleverede wear-bestillinger</a>.</li>
        <li><a href="<?php echo $this->url('show_wear');?>">se alle wear-typer</a>.</li>
        <li><a href="<?php echo $this->url('create_wear');?>">oprette en wear-type</a>.</li>
        <li><a href="<?php echo $this->url('wear_handout');?>">åbne wearuddelings-interfacet</a>.</li>
    </ul>
</p>
