<?php echo $this->getMessagesHtml();?>
<div id='wear-details'>
    <fieldset>
        <legend>Wear: <?php echo $this->wear->navn;?> - <a href="<?php echo $this->url('edit_wear',array('id' => $this->wear->id));?>">ret/slet</a></legend>
        <span class='label'>Id:</span> <span class='detail'><?php echo $this->wear->id;?></span><br class='clearit'/>
        <span class='label'>Navn:</span> <span class='detail'><?php echo $this->wear->navn;?></span><br class='clearit'/>
        <span class='label'>Engelsk titel:</span> <span class='detail'><?php echo $this->wear->title_en;?></span><br class='clearit'/>
        <span class='label'>Beskrivelse:</span> <span class='detail'><?php echo $this->wear->beskrivelse;?></span><br class='clearit'/>
        <span class='label'>Engelsk beskrivelse:</span> <span class='detail'><?php echo $this->wear->description_en;?></span><br class='clearit'/>
        <span class='label'>Maks bestilling:</span> <span class='detail'><?php echo $this->wear->max_order;?></span><br class='clearit'/>
        <hr/>
        <div id="attributes">
            <?php
                foreach($this->wear->getVariants() as $variant => $types){
                    ?><div class="attribute-variant"><?php
                    foreach ($types as $type => $attributes) {
                        ?>
                            <div class="attribute-type-list">
                                <h3><?=$type?></h3>
                        <?php
                        foreach($attributes as $att) {
                            ?><span class='attribute'><?=$att['desc_da']?></span><?php
                        }
                        ?>
                            </div>
                        <?php
                    }
                    ?></div><?php
                }
            ?>
        </div>
        <hr/>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Brugerkategori</th>
                    <th>Pris</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    if ($prices = $this->wear->getWearpriser()) :
                        foreach ($prices as $price) :
                            $navn = $price->getCategory()->navn;
                ?>
                <tr id='wp_<?php echo $price->id;?>'>
                    <td><?php echo $price->id;?></td>
                    <td><?=$navn;?></td>
                    <td><?php echo $price->pris;?></td>
                </tr>
                <?php endforeach;
                endif;?>
            </tbody>
        </table>
    </fieldset>
</div>
