<?php echo $this->getMessagesHtml();?>
<div>
    <table class='wear-breakdown'>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th colspan='<?php echo $this->size_count + 1;?>' class='wear-header'>Bestilt wear</th>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <?php foreach ($this->sizes as $size) : ?>
                    <th class='wear-subheader'><?php echo $size;?></th>
                <?php endforeach;?>
                <th class='wear-subheader'>Ialt</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->wear_pricetypes as $key => $price) :
                $ialt = 0;
            ?>
            <tr>
                <td class='wear-type'><?php echo $price->getWear()->navn;?>, <?php echo $price->getCategory()->navn;?></td>
                <?php if (empty($this->wear_data[$price->id])) : 
                    foreach ($this->sizes as $size) :?>
                        <td>0</td>
                    <?php endforeach;?>
                <?php else :
                    foreach ($this->sizes as $size) :
                        $col_done = false;
                            foreach ($this->wear_data[$price->id] as $data) :
                                if ($data['size'] == $size && $data['wearpris_id'] == $price->id) : ?>
                            <td class='alt'>
                                <a href="<?php echo $this->url('detailed_mini_list', array('type' => $price->id, 'size' => $size));?>"><?php echo $data['antal'];?></a>
                            </td>
                            <?php
                                $ialt += $data['antal'];
                                $col_done = true;
                                endif;
                            endforeach;
                        if (!$col_done) :?>
                    <td>0</td>
                        <?php endif;
                    endforeach; ?>
                <?php endif;?>
                <td class='alt'><?php echo $ialt;?></td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>
