<?php echo $this->getMessagesHtml();?>
<div>
    <table class='wear-breakdown'>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th colspan='<?php echo $this->size_count + 1;?>' class='wear-header'>Bestilt wear</th>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <th class='wear-subheader'>Ialt</th>
                <?php foreach ($this->sizes as $size) : ?>
                    <th class='wear-subheader'><?php echo $size['size_name_da'];?></th>
                <?php endforeach;?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->wear_types as $key => $wear) :
                $ialt = 0;
            ?>
            <tr>
                <td class='wear-type'>(<?=$wear->id?>) <?=$wear->navn;?></td>
                <?php foreach($this->wear_data[$wear->id] as $antal) {
                    $ialt += $antal;
                } ?>
                <td class='alt'><?php echo $ialt;?></td>
                <?php if (empty($this->wear_data[$wear->id])) : 
                    foreach ($this->sizes as $size) :?>
                        <td>0</td>
                    <?php endforeach;?>
                <?php else :
                    foreach ($this->sizes as $size) :
                        if (isset($this->wear_data[$wear->id][$size['size_id']])) {
                            ?>
                                <td class='alt'>
                                    <a href="<?php echo $this->url('detailed_mini_list', array('type' => $wear->id, 'size' => $size['size_id']));?>">
                                        <?=$this->wear_data[$wear->id][$size['size_id']]?>
                                    </a>
                                </td>
                            <?php
                        } else {
                            ?>
                                <td>0</td>
                            <?php        
                        }
                    endforeach; ?>
                <?php endif;?>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>
<!-- <?php echo json_encode($this->wear_data, JSON_PRETTY_PRINT); ?> -->
