<?php echo $this->getMessagesHtml();?>
<div>
    <table class='wear-breakdown'>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th colspan='<?php echo $this->size_count + 1;?>' class='wear-header'>Bestilt wear</th>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <?php foreach ($this->sizes as $size) : ?>
                    <th class='wear-subheader'><?php echo $size['size_name_da'];?></th>
                <?php endforeach;?>
                <th class='wear-subheader'>Ialt</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->wear_types as $key => $wear) :
                $ialt = 0;
            ?>
            <tr>
                <td class='wear-type'><?=$wear->navn;?></td>
                <?php if (empty($this->wear_data[$wear->id])) : 
                    foreach ($this->sizes as $size) :?>
                        <td>0</td>
                    <?php endforeach;?>
                <?php else :
                    foreach ($this->sizes as $size) :
                        $col_done = false;
                            foreach ($this->wear_data[$wear->id] as $data) :
                                if ($data['size'] == $size['size_id'] && $data['wear_id'] == $wear->id) : ?>
                            <td class='alt'>
                                <a href="<?php echo $this->url('detailed_mini_list', array('type' => $wear->id, 'size' => $size['size_id']));?>"><?php echo $data['antal'];?></a>
                            </td>
                            <?php
                                $ialt += $data['antal'];
                                $col_done = true;
                                endif;
                            endforeach;
                        if (!$col_done) :?>
                    <td>0</td>
                        <?php endif;
                    endforeach; ?>
                <?php endif;?>
                <td class='alt'><?php echo $ialt;?></td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>
