<?= $this->getMessagesHtml();?>
<div id='sms-dialog'>
    <fieldset>
        <legend><b>Send beskeder (SMS eller via app)</b></legend>
        <p>Antal modtagere: <?php echo count($this->receivers);?></p>
        <form action="<?php echo $this->url('sms_send');?>" method='post'>
            <label for='afsender'>Afsender:</label> <input type='text' name='sms_afsender' id='afsender' value='Fastaval'/><br/>
            <label for='besked'>Besked:</label> <textarea name='sms_besked' id='besked'></textarea><br/>
            <input type='submit' value='Send beskeder'/>
        </form>
        <p>Du sender til:<br/>
        <?php foreach ($this->receivers as $receiver) : ?>
            <?php echo e($receiver->mobiltlf);?> - <?php echo e($receiver->fornavn);?> <?php echo e($receiver->efternavn);?><br/>
        <?php endforeach;?>
    </fieldset>
</div>
