<?= $this->getMessagesHtml();?>
<div class='middleboxes'>
	<fieldset>
		<legend>Download deltagerliste som regneark</legend>
		<div class="outer-container">
			<form action="" method="post" name="frmListExport" id="frmListExport" enctype="multipart/form-data">
        <input type="hidden" id="ids" name="ids" value="<?=$this->id_ranges?>">
				<div>
					<label>Vælg Filtype</label>
					<select name="filetype" id="participant_list_filetype">
						<option value ="csv">Comma Seperated Values (.csv)</option>
					</select>
					<button type="submit" id="exportparticipantlist" name="exportparticipantlist" class="btn-submit">Download</button>
				</div>
			</form>
		</div>
	</fieldset>
	<fieldset>
    <div>
      <table>
        <thead>
          <th>ID</th>
          <th>Navn</th>
          <th>Kaldenavn</th>
          <th>Fødselsdato</th>
          <th>Kontakt person</th>
          <th>Kommentar</th>
          <th>Wear</th>
          <th>Aktiviteter (tilmeldt)</th>
          <th>Aktiviteter (pladser)</th>
        </thead>
        <tbody>
          <?php foreach($this->participants as $p) { ?>
            <tr>
              <td><?=$p->id?></td>
              <td><?=$p->getName()?></td>
              <td><?=$p->nickname?></td>
              <td><?=preg_replace("/ \d{2}:\d{2}:\d{2}/", "", $p->birthdate)?></td>
              <td><?=str_replace("\n", "<br>", $p->note->junior_ward->content ?? "")?></td>
              <td><?=str_replace("\n", "<br>", $p->note->junior_comment->content ?? "")?></td>
              <td>
                <?php foreach($p->getWear() as $w) {
                  echo $w->getWearName().($w->size != 1 ? " - ".$w->getSizeName() : "")."<br>";
                } ?>
              </td>
              <td>
                <?php
                  $tilmeldinger = $p->getTilmeldinger();
                  uasort($tilmeldinger, function($a, $b) {
                    return $a->prioritet - $b->prioritet;
                  });

                  foreach($tilmeldinger as $t) {
                    $activity = $t->getAktivitet();
                    $afvikling = $t->getAfvikling();
                    preg_match("/\d{4}-\d{2}-\d{2} (\d{2}:\d{2}):\d{2}/", $afvikling->start,$start);
                    preg_match("/\d{4}-\d{2}-\d{2} (\d{2}:\d{2}):\d{2}/", $afvikling->slut,$end);
                    echo "($t->prioritet) $activity->navn ($start[1] - $end[1])<br>";
                  } 
                ?>
              </td>
            </tr>
          <?php } ?>
        </tbody>
      <table>
    </div>
  </fieldset>
</div>