<div class='edit_details'>
    <form action='' method='post'>
        <fieldset id='edit_pages'>
            <legend>Opdater Aktivitets-tilmeldinger</legend>
            <table>
                <tr>
                    <td>
                        <select id='aktivitet_navn'>
                            <option value=''>Vælg</option>
                            <?php foreach ($this->aktiviteter as $activity) :
                                if ($activity->kan_tilmeldes != 'nej') :?>
                                <option value="<?php echo e($activity->id);?>"><?php echo e($activity->navn);?> / <?php echo e($activity->title_en);?></option>
                                <?php endif;
                            endforeach; ?>
                        </select>
                        <select id='aktivitet_tid'>
                        </select>
                        <select id='aktivitet_sl' style='display: none'>
                            <option value=''>Vælg</option>
                            <option value='spiller'>Spiller</option>
                            <option value='spilleder'>Spilleder</option>
                        </select>
                        <select id='aktivitet_prio' style='display: none'>
                            <option value='1'>1. prioritet</option>
                            <option value='2'>2. prioritet</option>
                            <option value='3'>3. prioritet</option>
                            <option value='4'>4. prioritet</option>
                        </select><br/>
                        <input type='button' id='aktivitet_tilfoej' value='Tilføj Tilmelding'/>
                    </td>
                    <td>
                        <table id='aktivitet_edit'>
                            <tbody>
                                <?php foreach ($this->deltager->getTilmeldinger() as $tilmelding) :
                                    $afv = $tilmelding->getAfvikling();?>
                                <tr>
                                    <td class='choice'><input type='hidden' name='afvikling_id[]' value='<?= $afv->id;?>'/><input type='hidden' name='type[]' value='<?= e($tilmelding->tilmeldingstype);?>'/><input type='hidden' name='prioritet[]' value='<?= $tilmelding->prioritet;?>'/><?= e($tilmelding->getAktivitet()->navn);?> / <?= e($tilmelding->getAktivitet()->title_en);?> &mdash; <?= e($tilmelding->tilmeldingstype);?>, <?= $this->replaceDayNames(date('D H:i', strtotime($afv->start)) . '-' . date('H:i', strtotime($afv->slut)));?>, <?= $tilmelding->prioritet;?>. prioritet</td>
                                    <td><input type='button' value='Slet'/></td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </table>
            <hr/>
            <input type='submit' class='centersubmits' value='Opdater' name='update_tilmeldinger'/>
        </fieldset>
    </form>
    <script src='<?php echo $this->public_uri;?>js/imwedit.js' type='text/javascript'></script>
    <script type='text/javascript'>
        madwearedit.public_uri = '<?php echo $this->public_uri;?>';
        madwearedit.setupTilmeldinger();
        madwearedit.deltager_id = <?php echo $this->deltager->id;?>;
    </script>
</div>
