<h2>Påmindelse om betaling til Fastaval 2016</h2>
<p>Hej <?= e($this->participant->fornavn);?> <?= e($this->participant->efternavn);?>,</p>
<p>&nbsp;</p>
<p>Vi skriver til dig, fordi vi ikke kan se, at du har betalt for din tilmelding til Fastaval 2016,
og derfor tillader vi os at sende denne påmindelse.</p>

<p>Har du allerede betalt skal du selvfølgelig bare se bort fra denne email - så mangler vi bare
at få ajourført vore systemer.</p>

<p>Har du ikke betalt, så husk at deadline for din betaling er <?= $this->payment_day;?>. Hvis du ikke betaler inden denne dato, vil din tilmelding blive annulleret. Du kan betale ved at klikke på dette link:</p>

<p><a href="<?= $this->payment_url;?>"><?= $this->payment_url;?></a></p>

<p>Det udestående beløb er på <?= e($this->payment_remainder);?>kr, og betalingen foregår via
Rollespil.dk. Læg mærke til at de lægger et gebyr på mellem 3,- og 14,-
(afhængigt at beløbets størrelse), samt et kort-afhængigt gebyr (omkring 0.7% på Dankort og 3.75% på udenlandsk
udstedte kort) oven i prisen.</p>

<h4>Betaling via bankoverførsel</h4>
<p>Har du ikke mulighed for at betale online, så kan du også gøre det via bankoverførsel.
Det er dog noget dyrere, fordi det involverer mere arbejde. Derfor lægger tager vi et
gebyr på 10,- for betaling via bankoverførsel.</p>
<p>For at betale via bankoverførsel skal du benytte dig af informationerne herunder:</p>
<ul>
    <li>Du skal overføre <?= e($this->payment_remainder + 10);?>kr. (<?= e($this->payment_remainder);?>kr + 10kr i gebyr) enten via indbetalingskort eller direkte overførsel
    <li>Ved indbetaling på indbetalingskort: Kortart: +73 / Kreditornr.: 84520098</li>
    <li>Ved bankoverførsel til vores bankkonto: Reg.: 9314 / Kontonr.: 4573884464</li>
    <li>Ved indbetaling fra en bank UDENFOR Danmark så kontakt venligst <a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a></li>
</ul>
<p>&nbsp;</p>
<p><strong>Vi glæder os til at se dig på Fastaval 2016!</strong></p>
<p>Mvh Fastaval</p>
