<h2>Reminder of payment for Fastaval 2016</h2>
<p>Hi <?= e($this->participant->fornavn);?> <?= e($this->participant->efternavn);?>,</p>
<p>&nbsp;</p>
<p>We&#39;re writing to you because we haven&#39;t registered a payment from you for Fastaval 2016, and so we thought we&#39;d take the opportunity to remind you.</p>

<p>If you already paid, just ignore this email - we are just lagging a bit behind
getting our information up-to-date.</p>

<p>If you haven&#39;t already paid, remember that your deadline for paying is <?= $this->payment_day;?>.
If you don&#39;t pay before this date your sign up will be canceled. You can pay here:</p>

<p><a href="<?= $this->payment_url;?>"><?= $this->payment_url;?></a></p>

<p>The amount is <?= e($this->payment_remainder);?>DKK, and payment takes place through Rollespil.dk. Note that
they add a fee of between 3DKK and 14DKK (depending upon the amount), as well as a credit-card fee (0.75% for
Dankort and 3.75% on non-Danish credit-cards).</p>

<h4>Payment by banktransfer</h4>
<p>If you cannot pay online, it is also possible to pay through banktransfer. This is a bit more expensive,
however, as it involves more work. Because of that, there is a fee of 10DKK on bank transfers.</p>
<p>To pay by banktransfer, use the information below:</p>
<ul>
    <li>Payment due is <?= e($this->payment_remainder + 10);?>DKK (<?= e($this->payment_remainder);?>DKK + 10DKK fee)</li>
    <li>From a Danish bank: Reg.: 9314 / Account: 4573884464</li>
    <li>Paying from a bank outside of Denmark, please contact <a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a></li>
</ul>
<p>&nbsp;</p>
<p><strong>We look forward to seeing you at Fastaval 2016!</strong></p>
<p>Best,</p>
<p>Fastaval</p>
