<p>
    <b>Karma-status (udregnet ud fra <?php echo $this->karma_avg['count'];?> deltagere med tilmeldinger):</b><br/>
    <table>
        <tbody>
            <tr>
                <td>gennemsnitlig relativ karma</td><td><?php echo $this->karma_avg['rel_karma'];?></td>
            </tr>
            <tr>
                <td>mindste relativ karma</td><td><?php echo $this->karma_avg['min_rel'];?></td>
            </tr>
            <tr>
                <td>højeste relativ karma</td><td><?php echo $this->karma_avg['max_rel'];?></td>
            </tr>
            <tr>
                <td>gennemsnitlig absolut karma</td><td><?php echo $this->karma_avg['abs_karma'];?></td>
            </tr>
            <tr>
                <td>mindste absolut karma</td><td><?php echo $this->karma_avg['min_abs'];?></td>
            </tr>
            <tr>
                <td>højeste absolut karma</td><td><?php echo $this->karma_avg['max_abs'];?></td>
            </tr>
        </tbody>
    </table>
</p>
