<p>
    <b>Karma-status (udregnet ud fra <?php echo $this->karma_avg['count'];?> deltagere med tilmeldinger):</b><br/>
    <table>
        <tbody>
            <tr>
                <td>gennemsnitlig karma</td><td><?php echo $this->karma_avg['avg'];?></td>
            </tr>
            <tr>
                <td>mindste karma</td><td><?php echo $this->karma_avg['min'];?></td>
            </tr>
            <tr>
                <td>højeste karma</td><td><?php echo $this->karma_avg['max'];?></td>
            </tr>
        </tbody>
    </table>
</p>
