<?php echo $this->getMessagesHtml();?>
<p>Du kan:
    <ul>
        <li><a href="<?php echo $this->url('vis_alle_deltagere');?>">se alle deltagere</a> eller <a href="<?php echo $this->url('vis_alle_deltagere');?>?show_search_box=true">søge på deltagere</a>.</li>
        <li>se deltagere <a href="<?php echo $this->url('deltagere_karmalist');?>">sorteret efter karma</a>.</li>
        <li>se <a href="<?php echo $this->url('vis_spilledere');?>">tilmeldte og fordelte spilledere</a>.</li>
        <li><a href="<?php echo $this->url('opret_deltager');?>">oprette en deltager</a>.</li>
        <li>se <a href="<?php echo $this->url('economy_breakdown');?>">oversigt over budgetteret indkomst</a>.</li>
        <li>se <a href="<?php echo $this->url('detailed_budget');?>">detaljeret budget</a>.</li>
        <li>se <a href="<?php echo $this->url('karma_stats');?>">karma stats</a>.</li>
        <li><a href="<?php echo $this->url('checkin_interface');?>">checke deltagere ind</a>.</li>
    </ul>
</p>
