<?=$this->getMessagesHtml()?>
<h1>Info til navneskilte</h1>

<div id="nametag-forms" class='middleboxes'>
	<fieldset>
		<legend>Hent som regneark</legend>
		<div class="outer-container">
			<form action="" method="post" name="frmExcelDownload" id="frmExcelDownload" enctype="multipart/form-data">
				<div>
					<label>Vælg Filtype</label>
					<select name="filetype" id="tag_info_filetype">
						<option value ="xlsx">Office Open XML (.xlsx) Excel 2007 and above</option>
            <option value ="csv">CSV Tekstfil hvor celler er seppareret med semicolon</option>
					</select>
					<button type="submit" id="download_tag_list" name="download_tag_list" class="btn-submit">Hent</button>
				</div>
			</form>
		</div>
	</fieldset>
	<fieldset>
		<legend>Hent billeder</legend>
		<div class="outer-container">
			<form action="" method="post" name="frmImageDownload" id="frmImageDownload" enctype="multipart/form-data">
				<div>
					<label>Vælg billeder</label>
					<select name="images" id="tag_info_images">
						<option value ="both">Fotos og stregkoder</option>
            <option value ="photos">Kun Fotos</option>
            <option value ="barcodes">Kun Stregkoder</option>
					</select>
					<button type="submit" id="download_tag_images" name="download_tag_images" class="btn-submit">Hent</button>
				</div>
			</form>
		</div>
	</fieldset>
</div>

<div class='middleboxes'>
<fieldset>
<table>
  <thead>
    <tr>
      <th>ID:</th>
      <th>Kaldenavn:</th>
      <th>Pronomen:</th>
      <th>Stregkode:</th>
      <th>Område:</th>
      <th>Billede:</th>
    </tr>
  </thead>
  <tbody>

<?php

$count = 0;
foreach ($this->participants as $participant) {
  $nickname = !empty($participant->nickname) ? $participant->nickname: $participant->getName(); 

  $class = 'class ="alterngrey"'
  ?>
    <tr <?=$count % 2 ? $class : ""?>>
      <td><?=$participant->id?></td>
      <td><?=$nickname?></td>
      <td><?=$participant->getPronoun()?></td>
      <td class='align-right'><img class='barcode-image' src='/participant/ean8sheet/<?= $participant->id;?>' alt='barcode'/></td>    
  <?php

  if ($participant->isArrangoer()) {
    ?>
      <td><?=$participant->arbejdsomraade?></td>
      <td><img src="<?=$this->photos[$participant->id]?>" alt=""/></td>
    <?php
  } else {
    ?>
      <td></td>
      <td></td>
    <?php
  }

  ?>
    </tr>
  <?php
  $count++;
}

?>
  </tbody>
</table>
</fieldset>
</div>