<h2>Missing payment for Fastaval 2018</h2>
<p>Dear <?= e($this->participant->fornavn);?> <?= e($this->participant->efternavn);?>,</p>
<p>&nbsp;</p>
<p>We are writing you because we haven&#39;t received payment from you for Fastaval 2018. Because of this your signup has been cancelled.</p>

<p>If you have already paid, then please contact us as soon as possible at <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>, so we can clear up the problem of payment and signup. Remember to include details of how and when you paid, as well as name and signup ID.</p>
<p>&nbsp;</p>
<p>Best,</p>
<p>Fastaval</p>
