<h2>Manglende betaling til Fastaval 2017</h2>
<p>Hej <?= e($this->participant->fornavn);?> <?= e($this->participant->efternavn);?>,</p>
<p>&nbsp;</p>
<p>Vi skriver til dig, fordi vi ikke har modtaget din betaling for Fastaval 2017. Derfor er din tilmelding nu blevet annulleret.</p>

<p>Har du allerede betalt så kontakt os hurtigst muligt på <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>, så vi kan få styr på både betalingen og tilmeldingen. Husk detaljer omkring hvordan og hvornår du har betalt, samt navn og tilmeldings-nummer.</p>

<p>Mvh Fastaval</p>
