<h1>Reset password</h1>
<?php if ($this->updated) : ?>
    <?php if ($this->danish) : ?>
<h3>Password opdateret</h3>
    <?php else : ?>
<h3>Password updated</h3>
    <?php endif;?>
<?php else : ?>
<form action="<?= $this->url('participant_reset_password', array('hash' => md5('reset-pw-' . $this->participant->id . '-' . $this->participant->password)));?>" method="POST">
    <?php if ($this->danish) : ?>
<p>Indtast nyt password og bekræft det:</p>
<div><input type="text" name="password" required pattern=".{6,60}" placeholder="Password"/></div>
<div><input type="text" name="password_copy" required placeholder="Bekræft password"/></div>
<button type="submit">Opdatér password</button>
    <?php else : ?>
<p>Enter your new password and confirm it:</p>
<div><input type="text" name="password" required pattern=".{6,60}" placeholder="Password"/></div>
<div><input type="text" name="password_copy" required placeholder="Confirm password"/></div>
<button type="submit">Update password</button>
    <?php endif;?>
</form>
<?php endif;?>
