<h1>Evaluering af Fastaval <?=$this->year?></h1>

<p>Hej <?=$this->name?>!</p>

<p>
  Tusind tusind af hjertet tak for din deltagelse på Fastaval <?=$this->year?> - og en ekstra tusind tak, hvis du også
  arrangerede. 
</p>

<p>
  Hermed modtager du en evaluering af årets Fastaval, og vi ville blive så glade, hvis du vil bruge et par øjeblikke på
  at gå igennem den, så vi kan arbejde videre med at udvikle Fastaval i fremtiden.
</p>

<p>
  Evaluering tager ca. 5 min. og er delt op i forskellige kategorier med spørgsmål vedrørende de forskellige ting,
  Fastaval har at byde på.
</p>

<p>
  Hvis du var arrangør har vi nogle spørgsmål rettet til dit arbejde på Fastaval. Efterfølgende vil du blive
  introduceret for de samme spørgsmål som deltagerne.<br>
  Spørgeskemaet kan derfor virke en smule længere for arrangører, men denne første halvdel er rigtig vigtig for os!
</p>

<p>
  Link til evaluering: <a href="https://forms.gle/d9NKvpCdSSNwvHSw7">https://forms.gle/d9NKvpCdSSNwvHSw7</a>
</p>

<p>
  Tusind tak!<br>
  Vi glæder os til at se jer igen næste år.
</p>

<p>Bunkeren, Fastaval <?=$this->year?></p>

