<h1>Evaluation of Fastaval <?=$this->year?></h1>

<p>Hey <?=$this->name?>!</p>

<p>
  A thousand, thousand many thanks from the bottom of our heart for your participation at Fastaval <?=$this->year?> - and throw in
  another thousand thanks if you were an organizer. 
</p>

<p>
  You hereby recieve the evaluation for this year's Fastaval, and we would be so happy if you would spend a few moments
  answering it, so that we can further optimize Fastaval in the future.
</p>

<p>
  The evaluation only takes approx. 5 min. to answer and is split into different categories regarding the different
  things Fastaval has to offer. 
</p>

<p>
  If you were an organizer we have a few questions regarding your work at Fastaval. Afterwards you will be introduced
  to the same questions as the other participants.<br>
  Therefore the questionnaire can seem a bit longer for the organizers, but the first half is very important to us!
</p>

<p>
  Link to evaluation: <a href="https://forms.gle/d9NKvpCdSSNwvHSw7">https://forms.gle/d9NKvpCdSSNwvHSw7</a>
</p>

<p>
  Thousand thanks!<br>
  We look forward to seeing you again next year. 
</p>

<p>The Bunker, Fastaval <?=$this->year?></p>

