<h2>Påmindelse om betaling til Fastaval 2015</h2>
<p>Hej <?= e($this->participant->fornavn);?> <?= e($this->participant->efternavn);?>,</p>
<p>&nbsp;</p>
<p>Vi skriver til dig, fordi vi stadig ikke kan se din betaling for Fastaval 2015. Derfor tillader vi os at sende denne sidste påmindelse.</p>

<p>Har du allerede betalt må du meget gerne kontakte os på <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>, så vi kan få styr på betalingen.</p>

<p>Har du ikke betalt, så husk at deadline for din betaling er <strong><?= $this->payment_day;?></strong> (dvs. i morgen). Hvis du ikke betaler inden denne dato, <strong>vil din tilmelding blive annulleret</strong>. Du kan betale ved at klikke på dette link:</p>

<p><a href="<?= $this->payment_url;?>"><?= $this->payment_url;?></a></p>

<p>Det udestående beløb er på <?= e($this->payment_remainder);?>kr, og betalingen foregår via
Rollespil.dk. Læg mærke til at de lægger et gebyr på mellem 3,- og 14,-
(afhængigt at beløbets størrelse), samt et kort-afhængigt gebyr (omkring 0.7% på Dankort og 3.75% på udenlandsk
udstedte kort) oven i prisen.</p>

<h4>Betaling via bankoverførsel</h4>
<p>Har du ikke mulighed for at betale online, så kan du også gøre det via bankoverførsel.
Det er dog noget dyrere, fordi det involverer mere arbejde. Derfor lægger tager vi et
gebyr på 20,- for betaling via bankoverførsel.</p>
<p>For at betale via bankoverførsel skal du benytte dig af informationerne herunder:</p>
<ul>
    <li>Du skal overføre <?= e($this->payment_remainder + 20);?>kr. (<?= e($this->payment_remainder);?>kr + 20kr i gebyr) enten via indbetalingskort eller direkte overførsel
    <li>Ved indbetaling på indbetalingskort: Kortart: +73 / Kreditornr.: 84520098</li>
    <li>Ved bankoverførsel til vores bankkonto: Reg.: 9314 / Kontonr.: 4573884464</li>
    <li>Ved indbetaling fra en bank UDENFOR Danmark så kontakt venligst <a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a></li>
</ul>
<p>&nbsp;</p>
<p><strong>Vi glæder os til at se dig på Fastaval 2015!</strong></p>
<p>Mvh Fastaval</p>
