<h1>Thank you for signing up!</h1>
<p>
Your signup has been registered - with participant ID <strong><?=$this->participant->id?></strong>. Below you can see the information we have registered.
</p>
<p>
    You will recieve further information about your personal schedule, when we're closer to Fastaval.
</p>
<?php if ($this->participant->betalt_beloeb < $this->prices['total']) : ?>
<h2>Payment</h2>
<p>
    <?php if ($this->participant->betalt_beloeb == 0) : ?>
Your payment amounts to <strong><?=$this->prices['total']?></strong> DKK - deadline for payment is <?= $this->payment_day;?>. If you sign up after <?=$this->payment_day?>, payment is due same day as your signup.

    <?php else : ?>
You have already paid <?=$this->participant->betalt_beloeb?>DKK but it seems that you still owe <strong><?=($this->prices['total'] - $this->participant->betalt_beloeb)?></strong> DKK on your signup.
You can pay via the online-payment functionality, by bank transfer or upon arriving at Fastaval.
    <?php endif;?>
</p>
<p>
When paying remember to clearly state your name and participant ID which is: <strong><?=$this->participant->id?></strong>
</p>
<p>
If you're using the Danish MobilePay, you can transfer the money to 438490 (Alea).<br>
It's important that you pay from the same number as the one you entered during sign-up. If this isn't possible, please
email <a href=mailto:andreas@fastaval.dk>andreas@fastaval.dk</a> and we'll figure something out.
</p>
<p>
    You can also pay right away by using Paypal. Transfer to <a href="mailto:andreas@fastaval.dk.">andreas@fastaval.dk.</a>
    There is a 100DKK fee for paying with PayPal so you will need to transfer a total of 
    <?= ($this->prices['total'] - $this->participant->betalt_beloeb + 100);?> DKK
</p>
<p>
Alternatively you can pay by bank transfer - please note that there is a fee on bank transfer amounting to 20 DKK (which makes the amount to pay <strong><?=($this->prices['total'] - $this->participant->betalt_beloeb + 20)?></strong> DKK)<br/>
* Paying from a Danish bank, use these details: Reg.: 9314 / Accountnr.: 4573884464<br/>
* Our bank information is IBAN DK6693144573884464 and BIC SPNODK22.<br/>
* deadline for payment is the same here: <?=$this->payment_day?>
</p>
<?php endif;?>
<p>
<strong>Please note </strong>that you can change your signup details through the signup at <a href="www.fastaval.dk">www.fastaval.dk</a>, up until <?=$this->end_signup_changes_date?>. All you need is your e-mail address and this code: <strong><?=$this->participant->password?></strong>
</p>
<?php if ($this->participant_photo_upload_link) : ?>
<p>
As a volunteer/writer/designer you need to have a picture on your nametag, to be able to use your discount at Fastaval.
Please use the following link to <strong>upload a photo</strong> for it:
<a href="<?= $this->participant_photo_upload_link;?>"><?= $this->participant_photo_upload_link;?></a>
</p>
<?php endif;?>
<p>
    If you have any questions or need assistance, you're always welcome to contact us at <a href=mailto:info@fastaval.dk>info@fastaval.dk</a>
</p>
<p>
<b>See you at Fastaval <?=$this->con_year?>!</b>
</p>
<div>
<table style="width: 100%"><tbody>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Login<h3>
</td></tr>
<tr><td colspan="2">Participant ID:                         </td><td><?=$this->participant->id?></td></tr>
<tr><td colspan="2">Password:                               </td><td><?=$this->participant->password?></td></tr>

<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Practical<h3>
</td></tr>
<tr><td colspan="2">Name:                                   </td><td><?=$this->participant->getName()?></td></tr>
<tr><td colspan="2">Address:                                </td><td><?=$this->participant->adresse1?></td></tr>
<?php if ($this->participant->adresse2) : ?>
<tr><td colspan="2">                                        </td><td><?=$this->participant->adresse2?></td></tr>
<?php endif;?>
<tr><td colspan="2">Postalcode:                             </td><td><?=$this->participant->postnummer?></td></tr>
<tr><td colspan="2">City:                                   </td><td><?=$this->participant->by?></td></tr>
<tr><td colspan="2">Country:                                </td><td><?=$this->participant->getCountry('en')?></td></tr>
<?php if ($this->participant->mobiltlf) : ?>
<tr><td colspan="2">Mobile:                                 </td><td><?=$this->participant->mobiltlf?></td></tr>
<tr><td colspan="2">SMS-service during Fastaval:            </td><td><?=$this->participant->medbringer_mobil === 'ja' ? 'Yes' : 'No'?></td></tr>
<?php endif;?>
<tr><td colspan="2">Birthdate:                              </td><td><?=date('j. M Y', strtotime($this->participant->birthdate))?></td></tr>
<tr><td colspan="2">Email:                                  </td><td><?=$this->participant->email;?></td></tr>
<tr><td colspan="2">Language for communication:             </td><td>English</td></tr>
<tr><td colspan="2">Used name:                              </td><td><?=$this->participant->nickname?></td></tr>
<?php $pronouns = ['they' => 'they/them', 'her' => 'she/her', 'he' => 'he/him']?>
<tr><td colspan="2">Pronouns:                               </td><td><?=$pronouns[$this->participant->pronoun]?></td></tr>
<?php if ($this->participant->ungdomsskole) : ?>
<tr><td colspan="2">School/club:                            </td><td><?=$this->participant->ungdomsskole?></td></tr>
<?php endif;?>
<tr><td colspan="2">Alea membership:                        </td><td><?=!empty($this->entrance['alea-membership']) ? $this->prices['alea']." DKK" : 'No'?></td></tr>
<?php if (!empty($this->participant->note->junior_ward)) : ?>
<tr><td colspan="2">Contact for Junior participant:</td></tr>
<?php foreach(explode('\n', $this->participant->note->junior_ward->content) as $contact_line) : ?>
    <?php $parts = explode(": ", $contact_line, 2); ?>
<tr><td colspan="2"><?=$parts[0]?>:                         </td><td><?=e($parts[1])?></td></tr>
<?php endforeach;?>
<?php endif;?>

<?php if ($this->participant->isArrangoer()) : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Organizer, Auther or Desginger<h3>
</td></tr>
<?php $author = $this->participant->getCollection('author')?>
<?php if (empty($author)) : ?>
<tr><td colspan="2">Organizer:                              </td><td>Yes</td></tr>
<tr><td colspan="2">Work area:                              </td><td><?=$this->participant->arbejdsomraade?></td></tr>
<?php endif;?>
<?php if (in_array('role', $author)) : ?>
<tr><td colspan="2">Author:                                 </td><td>Yes</td></tr>
<tr><td colspan="2">Scenario:                               </td><td><?=$this->participant->getGame('en')?></td></tr>
<?php endif;?>
<?php if (in_array('board', $author)) : ?>
<tr><td colspan="2">Designer:                               </td><td>Yes</td></tr>
<tr><td colspan="2">Board game:                             </td><td><?=$this->participant->getGame('en')?></td></tr>
<?php endif;?>
<?php endif; // isArrangoer()?>

<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Entrance and sleeping<h3>
</td></tr>
<?php if (!empty($this->entrance['entrance-junior'])) : ?>
<tr><td colspan="2">Fastaval Junior                         </td><td><?=$this->item_prices['entrance-junior']?> DKK</td></tr>
<?php endif;?>
<?php if (!empty($this->entrance['entrance-partout'])) : ?>
<tr><td colspan="2">Every-day pass                          </td><td><?=$this->item_prices['entrance-partout']?> DKK</td></tr>
<?php endif;?>
<?php if (isset($this->entrance['entrance-day'])) foreach($this->entrance['entrance-day'] as $date => $value) : ?>
<tr><td colspan="2">Entrance <?=getWeekDay(date('N', $date), true)?>  <?=date('jS M', $date)?> </td><td><?=$this->item_prices['entrance-single']?> DKK</td></tr>
<?php endforeach;?>
<?php if (!empty($this->entrance['sleeping-partout'])) : ?>
<tr><td colspan="2">Sleeping area (all-days)                </td><td><?=$this->item_prices['sleeping-partout']?> DKK</td></tr>
<?php endif;?>
<?php if (isset($this->entrance['sleeping-day'])) foreach($this->entrance['sleeping-day'] as $date => $value) : ?>
<tr><td colspan="2">Sleeping area <?=getWeekDay(date('N', $date), true)?> <?=date('jS M', $date)?> </td><td><?=$this->item_prices['sleeping-single']?> DKK</td></tr>
<?php endforeach;?>
<?php $sleeping_area = $this->participant->getCollection('sleeping_area')?>
<?php if (in_array('regular', $sleeping_area)) : ?>
<tr><td colspan="2">Standard Dormitory:                     </td><td>Yes</td></tr>
<?php endif;?>
<?php if (!empty($this->entrance['Leje af madras'])) : ?>
<tr><td colspan="2">Renting a mattress                      </td><td><?=$this->item_prices['mattres']?> DKK</td></tr>
<?php endif;?>
<?php if (in_array('sober', $sleeping_area)) : ?>
<tr><td colspan="2">Quiet and sober dormitory:              </td><td>Yes</td></tr>
<?php endif;?>
<?php if (in_array('youth', $sleeping_area)) : ?>
<tr><td colspan="2">Youth dormitory:                        </td><td>Yes</td></tr>
<?php endif;?>
<?php if (in_array('organizer', $sleeping_area)) : ?>
<tr><td colspan="2">Organizer Dormitory:                    </td><td>Yes</td></tr>
<?php endif;?>
<?php if (!empty($this->participant->note->sleeping)) : ?>
<tr><td colspan="2">Comments regarding sleeping arrangements:</td></tr>
<tr><td colspan="2"><?=e($this->participant->note->sleeping->content)?></td></tr>
<?php endif;?>

<?php if (!empty($this->food)) : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Food<h3>
</td></tr>
<?php if (!$this->participant->financial_struggle) : ?>
<tr><td colspan="2">Financial support:                      </td><td>Yes</td></tr>
<?php endif;?>
<?php foreach ($this->food as $fooditem) : ?>
    <?php $food = $fooditem->getMad();?>
<tr><td colspan="2"><?=$food->title_en;?> - <?=getWeekDay(date('N', strtotime($fooditem->dato)), true)?> </td><td><?=$food->pris?> DKK</td></tr>
<?php endforeach;?>
<?php endif; // Food?>

<?php if (!empty($this->gds)) : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>The Hero Force<h3>
</td></tr>
<?php $max_shifts = $this->participant->desired_diy_shifts; ?>
<tr><td colspan="2">Maximum hero tasks:                     </td><td><?=$max_shifts == 0 ? 'No limit' : $max_shifts?></td></tr>
<tr><td colspan="2">Task signup:</td></tr>
<?php foreach ($this->gds as $gds_signup) : ?>
<tr><td colspan="2"><?=getWeekDay(date('N', strtotime($gds_signup->getDate())), true)?> <?=$gds_signup->getTextDescription('en')?></td></tr>
<?php endforeach;?>
<?php if (!empty($this->participant->note->gds)) : ?>
<tr><td colspan="2">Comments regarding hero tasks:</td></tr>
<tr><td colspan="2"><?=e($this->participant->note->gds->content)?></td></tr>
<?php endif;?>
<?php endif; // GDS?>

<?php if ($this->participant->ready_mandag == 'ja' || $this->participant->ready_tirsdag == 'ja') : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Preparation<h3>
</td></tr>
<?php if ($this->participant->ready_mandag == 'ja') : ?>
<tr><td colspan="2">Preparation Monday:                     </td><td>Yes</td></tr>
<?php endif;?>
<?php if ($this->participant->ready_tirsdag == 'ja') : ?>
<tr><td colspan="2">Preparation Tuesday:                    </td><td>Yes</td></tr>
<?php endif;?>
<?php endif; // Ready?>

<?php if (!empty($this->activities)) : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Activities<h3>
</td></tr>
<?php if ($this->participant->supergm == 'ja') : ?>
<tr><td colspan="2">Super scenario facilitator:             </td><td>Yes</td></tr>
<?php endif;?>
<?php if ($this->participant->gm_max > 0) : ?>
<tr><td colspan="2">Maximum facilitator scenarios:          </td><td><?=$this->participant->gm_max?></td></tr>
<?php endif;?>
<?php if ($this->participant->super_rules_guide == 'ja') : ?>
<tr><td colspan="2">Super game guide:                       </td><td>Yes</td></tr>
<?php endif;?>
<?php if ($this->participant->rules_guide_max > 0) : ?>
<tr><td colspan="2">Maksimum guide tasks:                   </td><td><?=$this->participant->rules_guide_max?></td></tr>
<?php endif;?>
<?php
    $lang = ['dansk' => 'Danish', 'engelsk' => 'English', 'skandinavisk' => 'Scandinavian'];
    $lang_text = [];
    $sprog = $this->participant->getCollection('sprog');
    foreach($sprog as $sp) $lang_text[] = $lang[$sp];
?>
<tr><td colspan="2">Languages for activities:               </td><td><?=implode(", ", $lang_text)?></td></tr>
<?php $max_games = $this->participant->desired_activities; ?>
<tr><td colspan="2">Maximum games:                          </td><td><?=$max_games == 0 ? 'No limit' : $max_games?></td></tr>
<?php foreach ($this->activities as $activity_signup) : ?>
    <?php $activity = $activity_signup->getActivity();
        $schedule = $activity_signup->getAfvikling();?>
<tr>
    <td><?= $activity->title_en?></td>
    <td><?=date('l H:i', strtotime($schedule->start))?></td>
    <td><?= $activity_signup->tilmeldingstype === 'spiller' ? 'Priority '.$activity_signup->prioritet  : 'Facilitator'?></td>
</tr>
    <?php endforeach;?>
<?php endif; // Activites?>

<?php if (!empty($this->wear)) : ?>
<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Wear<h3>
</td></tr>
<?php foreach ($this->wear as $order) : ?>
    <?php $price = $order->getWearpris();
      $name  = $order->getWearName('en');?>
<tr><td colspan="2"><?=$order->antal?> <?=$name?></td><td><?=$price->pris?> DKK</td></tr>
<?php endforeach;?>
<?php endif; // Wear?>

<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Extra<h3>
</td></tr>
<?php if (!empty($this->entrance['party1'])) : ?>
<tr><td colspan="2">Sparkling wine                          </td><td><?=$this->item_prices['party1']?> DKK</td></tr>
<?php endif;?>
<?php if (!empty($this->entrance['party2'])) : ?>
<tr><td colspan="2">Party ekstra 2 (placeholder)            </td><td><?=$this->item_prices['party2']?> DKK</td></tr>
<?php endif;?>
<?php if (!empty($this->entrance['party3'])) : ?>
<tr><td colspan="2">Party ekstra 3 (placeholder)            </td><td><?=$this->item_prices['party3']?> DKK</td></tr>
<?php endif;?>
<?php if (isset($this->rig_onkel)) : ?>
<tr><td colspan="2">Extra support:                          </td><td><?=$this->rig_onkel?> DKK</td></tr>
<?php endif;?>
<?php if (isset($this->hemmelig_onkel)) : ?>
<tr><td colspan="2">Secret support:                         </td><td><?=$this->hemmelig_onkel?> DKK</td></tr>
<?php endif;?>
<?php if (!empty($this->participant->note->comment)) : ?>
<tr><td colspan="2">Comments:</td></tr>
<tr><td colspan="2"><?=e($this->participant->note->comment->content)?></td></tr>
<?php endif;?>

<tr><td colspan="3" style="text-align: center; background-color: lightgray; border-top: 1px solid black; border-bottom: 1px solid black;">
    <h3>Price<h3>
</td></tr>
<tr><td colspan="2">Entrance                                </td><td><?=$this->prices['entrance']?> DKK</td></tr>
<tr><td colspan="2">Sleeping                                </td><td><?=$this->prices['sleeping']?> DKK</td></tr>
<tr><td colspan="2">Alea membership fee                     </td><td><?=$this->prices['alea']?> DKK</td></tr>
<tr><td colspan="2">Food &amp; party                        </td><td><?=$this->prices['food']?> DKK</td></tr>
<tr><td colspan="2">Activities                              </td><td><?=$this->prices['activities']?> DKK</td></tr>
<tr><td colspan="2">Wear                                    </td><td><?=$this->prices['wear']?> DKK</td></tr>
<tr><td colspan="2">Misc                                    </td><td><?=$this->prices['other-stuff']?> DKK</td></tr>
<tr><td colspan="2">Ticketfee                               </td><td><?=$this->prices['fees']?> DKK</td></tr>
<tr><td colspan="2">Total                                   </td><td><?=$this->prices['total']?> DKK</td></tr>
</tbody></table>
</div>