<p>Hej <?= e($this->participant->fornavn);?>,</p>

<p>Du har bedt om at få resat dit password - hvilket du
kan gøre via linket herunder.</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>Hvis du ikke selv har bedt om at få det tilsendt kan du se
bort fra denne mail - du får den enten fordi i er flere der
er tilmeldt med samme email adresse, eller fordi en anden
har tastet en forkert email adresse.</p>

<p>Venlige hilsner<br/>
Fastaval</p>
