<p>Hi <?= e($this->participant->fornavn);?>,</p>

<p>You have asked to have your password from the Fastaval
signup changed - this you can do using the link below.</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>If you haven&#39;t asked for this email yourself, it means
that someone else requested the change by accident or that more
than one person has signed up with this email address. In
either case you can ignore this email completely.</p>

<p>With kind regards<br/>
Fastaval</p>
