<h2>Kære <?=$this->name?>,</h2>

<p>Der er nogle få ting, vi gerne vil oplyse dig om, nu hvor Fastaval nærmer sig.</p>

<p>Du kan altid komme i kontakt med Vagthavende general på <strong>+45 61 40 92 65</strong>.</p>

<p>
  Du kan komme i kontakt med en tryghedsvært på <strong>+45 61 40 92 64</strong>. Læs mere her, om hvad tryghedsværterne
  kan hjælpe med: <a href="https://www.fastaval.dk/tryghed/">https://www.fastaval.dk/tryghed/<a>.
</p>

<p>
  Her kan du finde praktisk information om bl.a. Code of Care, Transport, Alkoholpolitik og GDS:<br>
  <a href="https://www.fastaval.dk/praktisk/praktiske-informationer/">https://www.fastaval.dk/praktisk/praktiske-informationer/</a>.
</p>

<p>
  <strong>Onsdag kl. 16 og torsdag kl. 14</strong> afholdes Introtur for nye deltagere på Fastaval. Her kan du stille alle dine
  spørgsmål, samt lære andre deltagere at kende. Turen starter i Fællesområdet.
</p>

<p>
  Er du interesseret i andre aktiviteter kan du se dem i årets program:<br>
  <a href="https://docs.google.com/spreadsheets/d/1o74ZwRc1mk57vc9B_As7COZvnV1xkzEJ/edit?usp=sharing&ouid=116358956480656601273&rtpof=true&sd=true">
    https://docs.google.com/spreadsheets/d/1o74ZwRc1mk57vc9B_As7COZvnV1xkzEJ/edit?usp=sharing&ouid=116358956480656601273&rtpof=true&sd=true
  </a>
</p>

<p>
  I år får alle deltagere, der har tilmeldt sig inden for tilmeldingsdeadlinen, et navneskilt med årets design på.
  Kontakt Informationen for at få dit navneskilt.<br>
  Ved Informationen kan du også hente forskellige typer badges, som hjælper med at kommunikere dit sprog, pronominer
  eller din ædru-tilstand til andre deltagere. 
</p>

<h2>Dit Fastavalprogram</h2>

<p>
  Holdlæggerne er tæt på at være færdige med at få aktiviteterne på plads, og du kan nu se nogle af de ting, du kommer
  til at lave på årets Fastaval. <strong>Vær opmærksom på, at der stadig kan forekomme ændringer</strong>.
</p>

<p>
  Du får adgang til at se dine detaljer (din tilmelding plus de forskellige aktiviteter du er blevet tildelt, spil
  samt GDS) ved at gå ind på: 
  <a href="http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a>
</p>

<p>
  Dit deltagernummer er <strong><?=$this->id?></strong><br>
  Du skal bruge din personlige kode for at få adgang - den er: <strong><?=$this->code?></strong>
</p>

<p>
  Samme deltagernummer og  kode bruges også til vores Android og iPhone apps - søg på Fastaval eller Fastavappen hvor
  du henter apps. Så gem gerne denne e-mail.
</p>

<h2>GDS-vagter</h2>

<p>
  GDS-puslespillet er næsten færdigt, <strong>så husk, at der stadig vil forekomme ændringer optil Fastaval</strong>. Tjek din
  deltagerseddel og opdater din app, når du ankommer på Fastaval. 
</p>

<p>
  Vi vil bede dig tjekke om du har fået en tjans på et tidspunkt, hvor du endnu ikke er befinder dig på Fastaval.
  Hvis du allerede nu kan se, at du ikke kan tage din tjans, bedes du skrive til GDS-ansvarlige, Nynne på
  <a href="mailto:nynnebrandt0125@gmail.com">nynnebrandt0125@gmail.com</a> - så finder vi en løsning!<br>
  Skulle det under Fastaval ske, at du ikke er i stand til at tage din tjans, f.eks. ved sygdom, så fortæl os det, så
  snart det er muligt. Så har vi nemlig tid til at finde en, der kan tage over. Du kan komme i kontakt med Nynne på
  tlf. nr. <strong>+45 61 40 92 63</strong> under Fastaval.
</p>

<p>
  Hvis du har spørgsmål ang. din tilmelding eller andet, så kontakt os på
  <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
</p>

<p>Vi glæder os til at se dig på Fastaval!</p>
