<h2>Dear <?=$this->name?>,</h2>

<p>
  We want to draw attention to an error in the previous participation mail.<br>
  The phone number to the General on duty is  <strong>+45 61 40 90 65</strong>.
</p>

<p>
  As of now, every individual program and DIT-shifts has been planned and distributed.<br>
  You can see your updated participation note in the link below.
</p>

<p>
  You gain access to your participation note here:
  <a href="http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a><br>
  Your personal code is: <strong><?=$this->code?></strong>
</p>

<p>
  Once again we will ask you to check whether or not you've been assigned a DIT-shift at a
  certain time where you aren't at Fastaval. If you can see by now that you can't do your shift,
  please write to the DIT-Commander-in-Charge, Nynne, at
  <a href="mailto:nynnebrandt0125@gmail.com">nynnebrandt0125@gmail.com</a>
  we will find a solution!<br>
  From Wednesday at 3 PM you can call the DIT-Commander-in-Charge at <strong>+45 61 40 92 63</strong>
</p>

<p>
  If you have chosen a sleeping area in the sober-only dormitory, youth dormitory or organizer
  dormitory, you can see which dormitory you've been assigned to on your participation note
  under "Messages".
</p>

<h2>Fastavals app</h2>

<p>
  This year Fastaval has an app, but you can't find it at your local App Store.
  Instead, you will find it at <a href="https://app.fastaval.dk">app.fastaval.dk</a>.<br>
  The log-in function isn't ready yet, but you will receive a SMS when you can log in and see
  your personal program.
</p>

<h2>Check-In in the information upon your arrival</h2>

<p>
  You check in to Fastaval at the Info and receive a bracelet that grants you access to
  Fastaval. In the Info you can behold the <strong>Wall of Info</strong> where you can find the practical
  information. 
</p>

<p>
  Opening Hours of the Info:
  <ul>
    <li>Wednesday 	3 PM - 9 PM</li>
    <li>Thu-Sat	9 AM - 9 PM</li>
    <li>Sunday	9 AM - 5 PM</li>
  </ul>
</p>

<p>
  If you have any other questions or are in need of help, the Infonauts at the Info will be more than willing to help.
</p>

<p>See you at Fastaval!</p>
