<h2>Dear <?=$this->name?>,</h2>

<p>
  Fastaval is getting close, we're getting more excited and it's time for your program for this year's Fastaval!
  First though, we have a few important pieces of information.
</p>

<p>You can always get in contact with Vagthavende General at <strong>+45 93 89 90 65</strong>.</p>

<p>
  You can always contact a Safety Host at <strong>+45 93 89 90 64</strong>. To learn more about what the Safety Hosts
  are all about please read here: <a href="https://www.fastaval.dk/en/tryghed/">https://www.fastaval.dk/en/tryghed/<a>.
</p>

<p>
  Here you can find practical information about stuff like Rules, Transport and Photo Policy<br>
  <a href="https://www.fastaval.dk/en/praktisk/praktiske-informationer/">https://www.fastaval.dk/en/praktisk/praktiske-informationer/</a>.
</p>

<p>
  <strong>Wednesday at 5:30 PM and at 10 AM on Thursday, Friday and Saturday </strong> there will be an Intro for new
  participants at Fastaval (in both English and Danish). Here you can ask all of your questions and get to know a whole
  bunch of awesome people. The Tour will start next to the Information.
</p>

<p>
  Are you interested in other activities you can see them in this year's program:
  <br><a href="https://docs.google.com/spreadsheets/d/15gfaKC7QFytopFxz5PPlMgMt87TKaPn3">
    Program for Fastaval 2023
  </a>
</p>

<p>
  If you signed up for all days before the deadline, you'll get a name tag with this year's design on it. Contact
  the Information to receive your name tag.<br>
  At the Information you can also collect several types of badges that help communicate your language, pronouns or your
  level of sobriety to your fellow participants.
</p>

<h2>Your Fastaval Program</h2>

<p>
  The Activity Planners are nearly done getting all of the activities in place, and now you can see a preview of the
  things you will do at this year's Fastaval. <strong>Please bear in mind that changes might occur</strong>.
</p>

<p>
  You get access to view the different activities you've been assigned, games and hero tasks. at: 
    <br><a href="https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a>
</p>

<p>
  Your participant number is <strong><?=$this->id?></strong><br>
  You will need to use your personal code to gain access - it is: <strong><?=$this->code?></strong>
</p>

<p>
  The participant number and code is also used on our app for Android and iPhone. Therefore REMEMBER to save this e-mail.
  You can find the app by searching for Fastaval in your Play/App store or through the following links:
  <br><a href="https://play.google.com/store/apps/details?id=dk.alea.fastaval.fastaval_app">Google Play</a>
  <br><a href="https://apps.apple.com/us/app/fastavappen/id6445799103">App Store</a>
</p>

<p>
  The app is still under development and updates will be released periodically. You're however welcome to download and
  have a look at it already.
  Errors and suggestions can be sent to <a href="mailto:it@fastaval.dk">it@fastaval.dk</a>.
</p>

<h2>The Hero Force</h2>

<p>
    If you're signed up for The Hero Force, you'll also be able to see your assigned tasks on your participant sheet.
</p>

<p>
  The puzzle assigning hero tasks is almost completed so <strong>remember that there might be changes up until Fastaval
  starts</strong>. Check your participant sheet and update your app when you arrive at Fastaval.
</p>

<p>
  We would like to invite all heroes to our <strong>Facebook group</strong>, so that way Fastaval and The Hero Force can
  be in close contact with each other:
  <br><a href="https://www.facebook.com/groups/1327673908098684">https://www.facebook.com/groups/1327673908098684</a>
</p>

<p>
  In this group you'll have the oportunity ask questions of the organizer responsible for The Hero Force, Nynne Brandt.
  She will also have an easier time getting in touch with you, in case some task comes up out of the blue and she needs
  heroes! 💪
</p>

<p>
  You can also use the group in case you need to exchange tasks with each other. REMEBER to let The Hero Force responsible
  Nynne know, so the changes can be properly registered in our system.
</p>

<p>
  If you can already now see that you won't be able to show up for a task, please contact the Hero Force responsible, Nynne at
  <a href="mailto:heltestyrken@fastaval.dk">heltestyrken@fastaval.dk</a> - we'll then find a solution!
</p>
<p>
  If during Fastaval, you're unable to do a task due to illness etc., please notify us as soon as possible.
  That way we'll have time to find someone else who can do it instead.
  <br>You can contact Nynne at <strong>+45 93 89 90 62</strong> during Fastaval.
</p>

<h2>Finally</h2>

<p>
  If you have any questions regarding your registration or other stuff, please contact us at
  <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
</p>

<p>We look forward to seeing you at Fastaval 2023!</p>
