<h2>Kære <?=$this->name?>,</h2>

<p>
  Nu nærmer Fastaval sig, spændingen stiger og det er tid til dit årlige Fastaval program! Men først lidt vigtig
  information.
</p>

<p>Du kan altid komme i kontakt med Vagthavende General på <strong>+45 93 89 90 65</strong>.</p>

<p>
  Du kan komme i kontakt med en Tryghedsvært på <strong>+45 93 89 90 64</strong>. Læs mere her, om hvad Tryghedsværterne
  kan hjælpe med: <a href="https://www.fastaval.dk/tryghed/">https://www.fastaval.dk/tryghed/<a>.
</p>

<p>
  Her kan du finde praktisk information om bl.a. Regler, Transport og Fotopolitik<br>
  <a href="https://www.fastaval.dk/praktisk/praktiske-informationer/">https://www.fastaval.dk/praktisk/praktiske-informationer/</a>.
</p>

<p>
  <strong>Onsdag kl. 17:30 samt torsdag, fredag og lørdag kl. 10</strong> afholdes Introtur for nye deltagere på Fastaval.
  Her kan du stille alle dine spørgsmål, samt lære andre deltagere at kende. Turen starter ved Informationen.
</p>

<p>
  Er du interesseret i andre aktiviteter kan du se dem i årets program:
  <br><a href="https://docs.google.com/spreadsheets/d/15gfaKC7QFytopFxz5PPlMgMt87TKaPn3">
    Program for Fastaval 2023
  </a>
</p>

<p>
  Har du bestilt partout billet og tilmeldt dig inden for deadlinen, får du et navneskilt med årets design på.
  Kontakt Informationen for at få dit navneskilt.<br>
  Ved Informationen kan du også hente forskellige typer badges, som hjælper med at kommunikere dit sprog, pronomier
  eller din ædru-tilstand til andre deltagere. 
</p>

<h2>Dit Fastavalprogram</h2>

<p>
  Holdlæggerne er tæt på at være færdige med at få aktiviteterne på plads, og du kan nu se nogle af de ting, du kommer
  til at lave på årets Fastaval. <strong>Vær opmærksom på, at der stadig kan forekomme ændringer</strong>.
</p>

<p>
  Du får adgang til at se dine tildelte aktiviteter, spil samt helteopgaver ved at gå ind på: 
  <br><a href="https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a>
</p>

<p>
  Dit deltagernummer er <strong><?=$this->id?></strong><br>
  Du skal bruge din personlige kode for at få adgang - den er: <strong><?=$this->code?></strong>
</p>

<p>
  Samme deltagernummer og kode bruges også til vores Android og iPhone apps. HUSK derfor at gemme denne e-mail.
  Du kan finde vore app ved at søge på Fastaval i din Play/App store eller med følgende links:
  <br><a href="https://play.google.com/store/apps/details?id=dk.alea.fastaval.fastaval_app">Google Play</a>
  <br><a href="https://apps.apple.com/us/app/fastavappen/id6445799103">App Store</a>
</p>

<p>
  Appen er stadig under udvikling og vil blive opdateret løbende, men man er velkommen til at hente den allerede nu.
  Fejl og forslag kan sendes til <a href="mailto:it@fastaval.dk">it@fastaval.dk</a>.
</p>

<h2>Heltestyrken</h2>

<p>
  Hvis du er tilmeldt Heltestyrken kan du også se din tildelte opgave på din deltagerseddel.
</p>

<p>
  Puslespillet med helteopgaver er næsten færdigt, <strong>så husk, at der stadig vil forekomme ændringer optil
  Fastaval</strong>. Tjek din deltagerseddel og opdater din app, når du ankommer på Fastaval. 
</p>

<p>
  Vi vil gerne invitere alle helte ind i en fælles Facebook-gruppe, så både Fastaval og Heltestyrken kan være i tæt
  kontakt med hinanden:
  <br><a href="https://www.facebook.com/groups/1327673908098684">https://www.facebook.com/groups/1327673908098684</a>
</p>

<p>
  I gruppen har i mulighed for at stille spørgsmål til den ansvarlige for Heltestyrken, Nynne Brandt, og hun kan nemt
  komme i kontakt med jer, skulle der opstå en spontan helteopgave og hun har brug for helte! 💪
</p>

<p>
  I kan også bruge gruppen til at bytte helteopgaver internt. HUSK at gøre Heltestyrkeansvarlige Nynne opmærksom på
  dette, så bytningen bliver registreret i vores system.
</p>

<p>
  Hvis du allerede nu kan se, at du IKKE kan møde op til din opgave, bedes du skrive til Heltestyrkeansvarlige, Nynne på
  <a href="mailto:heltestyrken@fastaval.dk">heltestyrken@fastaval.dk</a> - så finder vi en løsning!
</p>
<p>
  Skulle det under Fastaval ske, at du ikke er i stand til at tage din opgave, f.eks. ved sygdom, så fortæl os det, så
  snart det er muligt. Så har vi nemlig tid til at finde en, der kan tage over.
  <br>Du kan komme i kontakt med Nynne på tlf. nr. <strong>+45 93 89 90 62</strong> under Fastaval.
</p>

<h2>Til sidst</h2>

<p>
  Hvis du har spørgsmål ang. din tilmelding eller andet, så kontakt os på
  <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
</p>

<p>Vi glæder os til at se dig til Fastaval 2023!</p>
