<h2>Kære <?=$this->name?>,</h2>

<p>
  Vi vil gøre opmærksom på en fejl i tidligere deltagermail.<br>
  Tlf. nr. til Vagthavende general er <strong>+45 61 40 90 65</strong>.
</p>

<p>
  Nu er alles program fastlagt og GDS-vagter fordelt.<br>
  Du kan se din opdaterede deltagerseddel i linket nedenfor.
</p>

<p>
  Du får adgang til din deltagerseddel her: 
  <a href="http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a><br>
  Din personlige kode er: <strong><?=$this->code?></strong>
</p>

<p>
  Vi vil igen bede dig tjekke, om du har fået en GDS-tjans på et tidspunkt, hvor du endnu ikke
  befinder dig på Fastaval. Hvis du allerede nu kan se, at du ikke kan tage din tjans, bedes du
  skrive til GDS-ansvarlige Nynne på
  <a href="mailto:nynnebrandt0125@gmail.com">nynnebrandt0125@gmail.com</a>
  så finder vi en løsning!<br>
  Fra onsdag kl 15.00 kan du ringe til GDS-ansvarlige på <strong>+45 61 40 92 63</strong>
</p>

<p>
  Har du ønsket en soveplads i Ædrusovesalen, Ungdomssovesalen eller Arrangørsovesalen kan du
  under "Besked" på din deltagerseddel se, om du er blevet tildelt en plads i en af disse.
</p>

<h2>Fastavals app</h2>

<p>
  Fastaval har i år en ny app-løsning, men den hentes ikke fra din app store.<br>
  Den findes i stedet i din browser på <a href="https://app.fastaval.dk">app.fastaval.dk</a>.<br>
  Log-in funktionen er ikke klar endnu, men i vil få en SMS, når i kan kan logge ind og se
  jeres personlige program.<br>
  Den gamle Fastaval-app er ikke i brug længere og kan derfor slettes.
</p>

<h2>Tjek ind i informationen, når du ankommer</h2>

<p>
  Du tjekker ind på Fastaval i Infoen og får et armbånd, der giver adgang til Fastaval.
  I Infoen kan du også tage et kig på <strong>Wall of Info</strong>, hvor du kan finde praktisk information.
</p>

<p>
  Infoens åbningstider:
  <ul>
    <li>Onsdag 	15 - 21</li>
    <li>Tor-lør 		09 - 21</li>
    <li>Søndag 	09 - 17</li>
  </ul>
</p>

<p>
  Har du spørgsmål eller brug for hjælp, så er Infonauterne i Infoen altid glade for at hjælpe.
</p>

<p>Vi ses på Fastaval!</p>
