<h2>Dear <?=$this->name?>,</h2>

<p>Fastaval is almost here, and as such we have but a few things left to inform you.</p>

<p>You can always get in contact with Vagthavende General at <strong>+45 61 40 92 65</strong>.</p>

<p>
  You can always get in contact with a Safe Host at <strong>+45 61 40 92 64</strong>. To learn more about what the Safe
  Hosts are all about please read here: <a href="https://www.fastaval.dk/en/safety/">https://www.fastaval.dk/en/safety/<a>.
</p>

<p>
Here you can find practical information about stuff like Code of Care, Transport, Alcohol Policy and DIT.<br>
  <a href="https://www.fastaval.dk/en/practical/practical-information/">https://www.fastaval.dk/en/practical/practical-information/</a>.
</p>

<p>
  <strong>Wednesday at 5:10 PM and Thursday at 3:10 PM</strong> there will be an Intro for new participants at Fastaval
  in English. Here you can ask all of your questions and get to know a whole bunch of awesome people. The Tour will
  start in the Common Area. 
</p>

<p>
Are you interested in other activities you can see them in this year's program:<br>
  <a href="https://docs.google.com/spreadsheets/d/1o74ZwRc1mk57vc9B_As7COZvnV1xkzEJ/edit?usp=sharing&ouid=116358956480656601273&rtpof=true&sd=true">
    https://docs.google.com/spreadsheets/d/1o74ZwRc1mk57vc9B_As7COZvnV1xkzEJ/edit?usp=sharing&ouid=116358956480656601273&rtpof=true&sd=true
  </a>
</p>

<p>
  This year every participant who signed up before the deadline get a name tag with this year's design on it. Contact
  the Information to receive yours.<br>
  At the Information, you can collect several types of badges that help communicate your language, pronouns or your
  level of sobriety to your fellow participants.  
</p>

<h2>Your Fastaval Program</h2>

<p>
  The Activity Planners are nearly done getting all of the activities in place, and now you can see a preview of the
  things you will do at this year's Fastaval. <strong>Please bear in mind that changes might occur</strong>.
</p>

<p>
  You get access to view your details (your registration plus the different activities you've been dealt, games and DIT)
  at: 
  <a href="http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
    http://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
  </a>
</p>

<p>
  Your participation number is <strong><?=$this->id?></strong><br>
  You will need to use your personal code to gain access - it is: <strong><?=$this->code?></strong>
</p>

<p>
  The same participation number and code is also used on our app for Android and iPhone - search for Fastaval or
  Fastavappen where you get your apps. So remember this e-mail.
</p>

<h2>DIT Shifts</h2>

<p>
  The DIT jigsaw is almost completed so <strong>remember that there might be changes up until Fastaval</strong>. Check
  your participation slip and update your app when you arrive at Fastaval.
</p>

<p>
  To make sure that you haven't been given a job at a time you aren't at Fastaval, please check your schedule. If you can
  see that you can't take that job please contact the DIT Commander in Charge, Nynne at
  <a href="mailto:nynnebrandt0125@gmail.com">nynnebrandt0125@gmail.com</a> - we are going to find a solution!<br>
  If you during Fastaval are unable to do the job, due to sickness, for instance, please notify us as soon as possible.
  Then we can find one who can do it instead. You can get in contact with Nynne at <strong>+45 61 40 92 63</strong>
  during Fastaval.
</p>

<p>
  Remember that if you have any questions regarding your registration or other then contact us at
  <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
</p>

<p>We look forward to seeing you at Fastaval!</p>
