<p>Hi,</p>

<p>You have asked to have your password <?= $this->site;?> changed - this you can do using the link below.</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>Note that you have until <?= date('H:i, Y-m-d', time() + 20 * 60);?> to reset your password - afterwards the link is invalid.</p>

<p>If you haven&#39;t asked for this email yourself just ignore this email - if it should happen again, please notify us, so we can take action.</p>

<p>With kind regards<br/>
<?= $this->site;?></p>
